### ISSUE TITLE
"/bluemap purge" can start multiple times without any information at all

### ISSUE THREAD

**Issue by dringewald** [BlueMap-Minecraft/BlueMap#167]
**BlueMap Version:**
*Full version including the target, e.g. `v1.3.1`*

I am using:
- [No] mods (on the rendered world)
- [No] resourcepacks (in bluemaps `config/resourcepack` folder)

**Description:**
*Describe the bug in full detail, including a way to reproduce it.
Sometimes a full log of your server-startup or a crash-report can be of much help!*

When having a huge map (12500 Blocks) and you try to purge the tiles of this map, then the purge-command shows nothing, like it's not even doing anything. (No output in chat etc.).
If you use the same commend again, then after some time, you'll get an exception in the server.log.
`
[17:05:10 ERROR]: [BlueMap] Failed to purge map 'Default'!
java.io.FileNotFoundException: File does not exist: bluemap/web/data/Default/lowres/x9/z1/6.json.gz
        at de.bluecolored.shadow.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2377) ~[?:?]
        at de.bluecolored.shadow.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679) ~[?:?]
        at de.bluecolored.shadow.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575) ~[?:?]
        at de.bluecolored.shadow.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2372) ~[?:?]
        at de.bluecolored.shadow.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679) ~[?:?]
        at de.bluecolored.shadow.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575) ~[?:?]
        at de.bluecolored.shadow.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2372) ~[?:?]
        at de.bluecolored.shadow.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679) ~[?:?]
        at de.bluecolored.shadow.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575) ~[?:?]
        at de.bluecolored.shadow.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2372) ~[?:?]
        at de.bluecolored.shadow.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679) ~[?:?]
        at de.bluecolored.shadow.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575) ~[?:?]
        at de.bluecolored.bluemap.common.plugin.commands.Commands.lambda$purgeCommand$6(Commands.java:636) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
`

The problem is, that the first time that a player uses this command worked, but it did not show any output, which is in fact a problem, because you're just starting a new thread on the server to delete these huge amount of files.
I would sugest to use the "/bluemap status & /bluemap" command to show the output of the deletion or some chat information at least. As a second option it would be good to limit the command to 1 use at a time, so you don't get an error in the server console. Something like "Deletion is already in progress" in the chat would be good when using the same command twice or more often.

**Comment by TBlueF** [comment]
Fixed in 1.5.5
