### ISSUE TITLE
Web map is not displayed nothing

### ISSUE THREAD

**Issue by skyboooox** [BlueMap-Minecraft/BlueMap#23]
I have loaded as a sponge server mod
It's been 24 hours since loading and it prompts me
`Render-Threads are running!`
`Scheduled tile-updates: 0 + 1`
Then I opened the webpage and there was nothing on it
This is my web address
The webpage may not open because I am in China
![批注 2020-02-02 184513](https://user-images.githubusercontent.com/20927006/73607041-3a3e9600-45ec-11ea-878d-f91610a21243.png)

**Comment by skyboooox** [comment]
My bluemap.conf
```
accept-download: true

# This changes the amount of threads that BlueMap will use to render the maps.
# A higher value can improve render-speed but could impact performance on the host machine.
# This should be always below or equal to the number of available processor-cores.
# Zero or a negative value means the amount of of available processor-cores subtracted by the value.
# (So a value of -2 with 6 cores results in 4 render-processes)
# Default is -2
renderThreadCount: -2

# The folder where bluemap saves data-files it needs during runtime or to save e.g. the render-progress to resume it later.
data: "bluemap"

# The webroot of the website that displays the map.
webroot: "bluemap/web"

# Unncomment this to override the path where bluemap stores the data-files.
# Default is "<webroot>/data"
#webdata: "path/to/data/folder"

webserver {
	# With this setting you can disable the integrated web-server.
	# This is usefull if you want to only render the map-data for later use, or if you setup your own webserver.
	# Default is enabled
	enabled: true

	# The IP-Adress that the webserver binds to.
	# If this setting is commented out, bluemap tries to find the default ip-adress of your system.
	# If you only want to access it locally use "localhost".
	#ip: "localhost"
	#ip: "127.0.0.1"

	# The port that the webserver listenes to.
	# Default is 8100
	port: 8100

	# Max number of simultaneous connections that the webserver allows
	# Default is 100
	maxConnectionCount: 100
}

# This is an array with multiple configured maps.
# You can define multiple maps, for different worlds with different render-settings here
maps: [

	{
		# The id of this map
		# Should only contain word-charactes: [a-zA-Z0-9_]
		id: "world2"
	
		# The name of this map
		# This defines the display name of this map, you can change this at any time
		# Default is the id of this map
		name: "生存"
		
		# The path to the save-folder of the world to render
		world: "world/world2"
		
		# The position on the world where the map will be centered if you open it.
		# This defaults to the world-spawn if you don't set it.
		#startPos: [500, -820]

		# If this is false, BlueMap tries to omit all blocks that are not visible from above-ground.
		# More specific: Block-Faces that have a sunlight/skylight value of 0 are removed.
		# This improves the performance of the map on slower devices by a lot, but might cause some blocks to disappear that should normally be visible.
		# Default is false
		renderCaves: false
		
		# AmbientOcclusion adds soft shadows into corners, which gives the map a much better look.
		# This has only a small impact on render-time and has no impact on the web-performance of the map.
		# The value defines the strength of the shading, a value of 0 disables ambientOcclusion.
		# Default is 0.25
		ambientOcclusion: 0.25

		# Lighting uses the light-data in minecraft to shade each block-face.
		# If this is enabled, caves and inside buildings without torches will be darker.
		# The value defines the strength of the shading and a value of 0 disables lighting (every block will be fully lit).
		# Default is 0.8
		lighting: 0.8
		
		# With the below values you can limit the map-render.
		# This can be used to ignore the nethers ceiling or render only a certain part of a world.
		# Default is no min or max value (= infinite bounds)
		#minX: -4000
		#maxX: 4000
		#minZ: -4000
		#maxZ: 4000
		#minY: 50
		#maxY: 126
				
		# Using this, BlueMap pretends that every Block out of the defined render-bounds is AIR,
		# this means you can see the blocks where the world is cut (instead of having a see-through/xray view).
		# This has only an effect if you set some render-bounds above.
		# Default is enabled
		renderEdges: true
		
		# With this set to true, the generated files for this world are compressed using gzip to save A LOT of space.
		# Files will be only 5% as big with compression!
		# Note: If you are using NGINX or Apache to host your map, you can configure them to serve the compressed files directly.
		# This is much better than disabling the compression.
		useCompression: true
		
		# HIRES is the high-resolution render of the map. Where you see every block.
		hires {
			# Defines the size of one map-tile in blocks.
			# If you change this value, the lowres values might need adjustment as well!
			# Default is 32
			tileSize: 32
			
			# The View-Distance for hires tiles on the web-map (the value is the radius in tiles)
			# Default is 4.5
			viewDistance: 4.5
		}
		
		# LOWRES is the low-resolution render of the map. Thats the model that you see if you zoom far out to get an overview.
		lowres {
			# Defines resolution of the lowres model. E.g. If the hires.tileSize is 32, a value of 4 means that every 8*8 blocks will be summarized by one point on the lowres map.
			# Calculation: 32 / 4 = 8
			# You can only use values that result in an integer if you use the above calculation!
			# Default is 4
			pointsPerHiresTile: 4
			
			# Defines the size of one lowres-map-tile in points.
			# Default is 50
			pointsPerLowresTile: 50
			
			# The View-Distance for lowres tiles on the web-map (the value is the radius in tiles)
			# Default is 7
			viewDistance: 7
		}
	}
	
	# Here another example for the End-Map
	# Things we don't want to change from default we can just omit
	{
		id: "end"
		name: "末地"
		world: "world/DIM1"
		
		# In the end is no sky-light, so we need to enable this or we won't see anything.
		renderCaves: true
		
		# Same here, we don't want a dark map. But not completely disabled, so we see the effect of e.g torches.
		lighting: 0.4
	}
	
	# Here another example for the Nether-Map
	{
		id: "nether"
		name: "地狱"
		world: "world/DIM-1"
		
		renderCaves: true
		lighting: 0.6
		
		# We slice the whole world at y:90 so every block above 90 will be air.
		# This way we don't render the nethers ceiling.
		maxY: 90
		renderEdges: true
	}

]
```

**Comment by TBlueF** [comment]
Did you use the `/bluemap render` command? 
Also, the path to your world seems odd:
```
# The path to the save-folder of the world to render
world: "world/world2"
```
if your world `world2` is directly in your server-folder try to use:
```
# The path to the save-folder of the world to render
world: "world2"
```

**Comment by skyboooox** [comment]
- Of course, I executed it after the initial configuration.

` bluemap render world2`
But he is still like this

- I just followed your suggestion and changed it to

```
# The path to the save-folder of the world to render
world: "world2
```
But something went wrong

```
> bluemap reload
[19:30:01] [Server thread/INFO] [nucleus]: Server 执行指令: /bluemap reload
[19:30:01] [Server thread/INFO] [minecraft/DedicatedServer]: Reloading BlueMap...
[19:30:01] [Thread-59/INFO] [bluemap]: WebServer closed.
[19:30:04] [Thread-104/ERROR] [bluemap]: Failed to load map 'world2': 'C:\Users\zcj92\Desktop\Minecraft\3sever - 10\world2' does not exist or is no directory!
java.io.IOException: null
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:155) ~[Plugin.class:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.reload(Plugin.java:344) ~[Plugin.class:?]
        at de.bluecolored.bluemap.common.plugin.Commands.lambda$executeReloadCommand$0(Commands.java:108) ~[Commands.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[19:30:04] [Thread-104/WARN] [bluemap]: Some render-tickets can not be loaded because the map (id: 'world2') does not exist anymore. They will be discarded.
[19:30:04] [Thread-104/ERROR] [bluemap]: Failed to reload BlueMap!
java.lang.NullPointerException: null
        at de.bluecolored.bluemap.common.RenderTicket.hashCode(RenderTicket.java:43) ~[RenderTicket.class:?]
        at java.util.HashMap.hash(Unknown Source) ~[?:1.8.0_231]
        at java.util.HashMap.putIfAbsent(Unknown Source) ~[?:1.8.0_231]
        at de.bluecolored.bluemap.common.RenderManager.createTicket(RenderManager.java:72) ~[RenderManager.class:?]
        at de.bluecolored.bluemap.common.RenderManager.createTickets(RenderManager.java:87) ~[RenderManager.class:?]
        at de.bluecolored.bluemap.common.RenderManager.readState(RenderManager.java:235) ~[RenderManager.class:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:214) ~[Plugin.class:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.reload(Plugin.java:344) ~[Plugin.class:?]
        at de.bluecolored.bluemap.common.plugin.Commands.lambda$executeReloadCommand$0(Commands.java:108) ~[Commands.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[19:30:04] [Thread-104/INFO] [minecraft/DedicatedServer]: There was an error reloading BlueMap! See the console for details!
```

**Comment by TBlueF** [comment]
Hmm, So your world is in the folder `...\3sever - 10\world\world2`? Then `world/world2` was correct..
Are there any files in `...\3sever - 10\bluemap\web\data\world2` ? There should be two folders `lowres` and `hires` with more folders and files in them.

**Comment by skyboooox** [comment]
NO
![批注 2020-02-02 200527](https://user-images.githubusercontent.com/20927006/73607917-5d227780-45f7-11ea-92cf-156a7ceaf5b2.png)

**Comment by skyboooox** [comment]
This is the directory structure of the `./world`
![批注 2020-02-02 200633](https://user-images.githubusercontent.com/20927006/73607966-dd48dd00-45f7-11ea-90c8-ce81424693f8.png)
![批注 2020-02-02 200630](https://user-images.githubusercontent.com/20927006/73607968-e174fa80-45f7-11ea-84dc-bcb5f76ef492.png)

**Comment by skyboooox** [comment]
I reloaded again, `.\bluemap\web\data`  Still no change

```
[20:14:52] [Server thread/INFO] [nucleus]: Server 执行指令: /bluemap reload
[20:14:52] [Server thread/INFO] [minecraft/DedicatedServer]: Reloading BlueMap...
[20:14:54] [Thread-225/INFO] [minecraft/DedicatedServer]: BlueMap reloaded!
> [20:14:54] [Thread-237/INFO] [bluemap]: WebServer started.
> bluemap render world2
[20:16:41] [Server thread/INFO] [nucleus]: Server 执行指令: /bluemap render world2
[20:16:41] [Thread-239/INFO] [minecraft/DedicatedServer]: Collecting chunks to render...
[20:16:42] [Thread-239/INFO] [minecraft/DedicatedServer]: 25750 chunks found!
[20:16:42] [Thread-239/INFO] [minecraft/DedicatedServer]: Collecting tiles for map 'world2'
[20:16:42] [Thread-239/INFO] [minecraft/DedicatedServer]: 7151 tiles found! Task created.
[20:16:42] [Thread-239/INFO] [minecraft/DedicatedServer]: All render tasks created! Use /bluemap to view the progress!
> bluemap
[20:16:49] [Server thread/INFO] [nucleus]: Server 执行指令: /bluemap
[20:16:49] [Server thread/INFO] [minecraft/DedicatedServer]:
[20:16:49] [Server thread/INFO] [minecraft/DedicatedServer]: Tile-Updates:
[20:16:49] [Server thread/INFO] [minecraft/DedicatedServer]:  Render-Threads are running!
[20:16:49] [Server thread/INFO] [minecraft/DedicatedServer]:  Scheduled tile-updates: 0 + 0
> bluemap
[20:18:50] [Server thread/INFO] [nucleus]: Server 执行指令: /bluemap
[20:18:50] [Server thread/INFO] [minecraft/DedicatedServer]:
[20:18:50] [Server thread/INFO] [minecraft/DedicatedServer]: Tile-Updates:
[20:18:50] [Server thread/INFO] [minecraft/DedicatedServer]:  Render-Threads are running!
[20:18:50] [Server thread/INFO] [minecraft/DedicatedServer]:  Scheduled tile-updates: 0 + 2
```

**Comment by TBlueF** [comment]
huh .. why is the render task disappearing ?
this is weired,..

Do you use a resourcepack?
Is it possible to send me the world2 so i can try to reproduce this?

**Comment by skyboooox** [comment]
-I did not add resourcepack
-I just modified it and reloaded it. Now it can display the `world`, but it still ca n’t display the `world2`. If my webpage can be accessed normally, you can check
```

##                          ##
##         BlueMap          ##
##                          ##
##  by Blue (Lukas Rieger)  ##
##  http://bluecolored.de/  ##
##                          ##

# By changing the setting (accept-download) below to TRUE you are indicating that you have accepted mojang's EULA (https://account.mojang.com/documents/minecraft_eula),
# you confirm that you own a license to Minecraft (Java Edition)
# and you agree that BlueMap will download and use this file for you: https://launcher.mojang.com/v1/objects/0f275bc1547d01fa5f56ba34bdc87d981ee12daf/client.jar
# (Alternatively you can download the file yourself and store it here: <data>/minecraft-client-1.12.2.jar)
# This file contains resources that belong to mojang and you must not redistribute it or do anything else that is not compliant with mojang's EULA.
# BlueMap uses resources in this file to generate the 3D-Models used for the map and texture them. (BlueMap will not work without those resources.)
# 2020-02-02T01:53:02
accept-download: true

# This changes the amount of threads that BlueMap will use to render the maps.
# A higher value can improve render-speed but could impact performance on the host machine.
# This should be always below or equal to the number of available processor-cores.
# Zero or a negative value means the amount of of available processor-cores subtracted by the value.
# (So a value of -2 with 6 cores results in 4 render-processes)
# Default is -2
renderThreadCount: -2

# The folder where bluemap saves data-files it needs during runtime or to save e.g. the render-progress to resume it later.
data: "bluemap"

# The webroot of the website that displays the map.
webroot: "bluemap/web"

# Unncomment this to override the path where bluemap stores the data-files.
# Default is "<webroot>/data"
#webdata: "path/to/data/folder"

webserver {
	# With this setting you can disable the integrated web-server.
	# This is usefull if you want to only render the map-data for later use, or if you setup your own webserver.
	# Default is enabled
	enabled: true

	# The IP-Adress that the webserver binds to.
	# If this setting is commented out, bluemap tries to find the default ip-adress of your system.
	# If you only want to access it locally use "localhost".
	#ip: "localhost"
	#ip: "127.0.0.1"

	# The port that the webserver listenes to.
	# Default is 8100
	port: 8100

	# Max number of simultaneous connections that the webserver allows
	# Default is 100
	maxConnectionCount: 100
}

# This is an array with multiple configured maps.
# You can define multiple maps, for different worlds with different render-settings here
maps: [

	{
		# The id of this map
		# Should only contain word-charactes: [a-zA-Z0-9_]
		id: "world"
	
		# The name of this map
		# This defines the display name of this map, you can change this at any time
		# Default is the id of this map
		name: "world"
		
		# The path to the save-folder of the world to render
		world: "world"
		
		# The position on the world where the map will be centered if you open it.
		# This defaults to the world-spawn if you don't set it.
		#startPos: [500, -820]

		# If this is false, BlueMap tries to omit all blocks that are not visible from above-ground.
		# More specific: Block-Faces that have a sunlight/skylight value of 0 are removed.
		# This improves the performance of the map on slower devices by a lot, but might cause some blocks to disappear that should normally be visible.
		# Default is false
		renderCaves: false
		
		# AmbientOcclusion adds soft shadows into corners, which gives the map a much better look.
		# This has only a small impact on render-time and has no impact on the web-performance of the map.
		# The value defines the strength of the shading, a value of 0 disables ambientOcclusion.
		# Default is 0.25
		ambientOcclusion: 0.25

		# Lighting uses the light-data in minecraft to shade each block-face.
		# If this is enabled, caves and inside buildings without torches will be darker.
		# The value defines the strength of the shading and a value of 0 disables lighting (every block will be fully lit).
		# Default is 0.8
		lighting: 0.8
		
		# With the below values you can limit the map-render.
		# This can be used to ignore the nethers ceiling or render only a certain part of a world.
		# Default is no min or max value (= infinite bounds)
		minX: -4000
		maxX: 4000
		minZ: -4000
		maxZ: 4000
		minY: 50
		maxY: 126
				
		# Using this, BlueMap pretends that every Block out of the defined render-bounds is AIR,
		# this means you can see the blocks where the world is cut (instead of having a see-through/xray view).
		# This has only an effect if you set some render-bounds above.
		# Default is enabled
		renderEdges: true
		
		# With this set to true, the generated files for this world are compressed using gzip to save A LOT of space.
		# Files will be only 5% as big with compression!
		# Note: If you are using NGINX or Apache to host your map, you can configure them to serve the compressed files directly.
		# This is much better than disabling the compression.
		useCompression: true
		
		# HIRES is the high-resolution render of the map. Where you see every block.
		hires {
			# Defines the size of one map-tile in blocks.
			# If you change this value, the lowres values might need adjustment as well!
			# Default is 32
			tileSize: 32
			
			# The View-Distance for hires tiles on the web-map (the value is the radius in tiles)
			# Default is 4.5
			viewDistance: 4.5
		}
		
		# LOWRES is the low-resolution render of the map. Thats the model that you see if you zoom far out to get an overview.
		lowres {
			# Defines resolution of the lowres model. E.g. If the hires.tileSize is 32, a value of 4 means that every 8*8 blocks will be summarized by one point on the lowres map.
			# Calculation: 32 / 4 = 8
			# You can only use values that result in an integer if you use the above calculation!
			# Default is 4
			pointsPerHiresTile: 4
			
			# Defines the size of one lowres-map-tile in points.
			# Default is 50
			pointsPerLowresTile: 50
			
			# The View-Distance for lowres tiles on the web-map (the value is the radius in tiles)
			# Default is 7
			viewDistance: 7
		}
	}
	
	# Here another example for the End-Map
	# Things we don't want to change from default we can just omit
	{
		id: "end"
		name: "end"
		world: "world/DIM1"
		
		# In the end is no sky-light, so we need to enable this or we won't see anything.
		renderCaves: true
		
		# Same here, we don't want a dark map. But not completely disabled, so we see the effect of e.g torches.
		lighting: 0.4
	}
	
	# Here another example for the Nether-Map
	{
		id: "nether"
		name: "nether"
		world: "world/DIM-1"
		
		renderCaves: true
		lighting: 0.6
		
		# We slice the whole world at y:90 so every block above 90 will be air.
		# This way we don't render the nethers ceiling.
		maxY: 90
		renderEdges: true
	}
		{
		id: "world2"
		name: "world2"
		world: "world/world2"
		
		renderCaves: true
		ambientOcclusion: 0.25
		lighting: 0.8
		renderEdges: true
		useCompression: true
		hires {
			tileSize: 32
			viewDistance: 4.5
		}
		lowres {
			pointsPerHiresTile: 4
			pointsPerLowresTile: 50
			viewDistance: 7
		}
	}
]

```

**Comment by zcj924** [comment]
This is world2 download link
https://kirakira8-my.sharepoint.com/:u:/g/personal/zcj924_ms_kirakira_xin/ERtJodDslTxKmpgZvLEKrKwBaFTHmWMTe1c8xrm6s9Tz5Q?e=uw9jU5

**Comment by TBlueF** [comment]
I can see your webpage.
I will test the world2 in a couple minutes..

**Comment by TBlueF** [comment]
Ahh, i already found the problem: 
All chunks are marked as not yet light-populated that means that the light-calculation has not been done yet by minecraft on all chunks.
BlueMap is skipping those chunks because it needs the light-data.
I don't know why there is no light-data yet, is that a mod world/dimension?

**Comment by skyboooox** [comment]
This is another world create with the Sponge plugin `Nucleus`

**Comment by TBlueF** [comment]
Hm, i fear i cant help you further here. This is not a bug with BlueMap but an issue with something else. Maybe Sponge or Nucleus. The light data is essential for BlueMap to render the world, and as long as it is missing it wont render :/

**Comment by skyboooox** [comment]
Okay thank you
