### ISSUE TITLE
Exception while doing some work (WARN)

### ISSUE THREAD

**Issue by pys078** [BlueMap-Minecraft/BlueMap#234]
### What i did / Steps to reproduce

i installed these mods/plugins 
![image](https://user-images.githubusercontent.com/7541452/129826836-d83bfb2e-f408-4589-9242-70290db5c286.png)

### Expected result

console said:

```
[10:27:44] [RenderManager-0-0/ERROR] [bluemap]: RenderManager(0): WorkerThread(0): Exception while doing some work!
java.lang.NullPointerException: null
at de.bluecolored.bluemap.core.map.hires.blockmodel.LiquidModelBuilder.build(LiquidModelBuilder.java:111) ~[LiquidModelBuilder.class:?]
at de.bluecolored.bluemap.core.map.hires.blockmodel.LiquidModelBuilder.build(LiquidModelBuilder.java:76) ~[LiquidModelBuilder.class:?]
at de.bluecolored.bluemap.core.map.hires.blockmodel.BlockStateModelFactory.createModel(BlockStateModelFactory.java:82) ~[BlockStateModelFactory.class:?]
at de.bluecolored.bluemap.core.map.hires.blockmodel.BlockStateModelFactory.createFrom(BlockStateModelFactory.java:61) ~[BlockStateModelFactory.class:?]
at de.bluecolored.bluemap.core.map.hires.blockmodel.BlockStateModelFactory.createFrom(BlockStateModelFactory.java:47) ~[BlockStateModelFactory.class:?]
at de.bluecolored.bluemap.core.map.hires.HiresModelRenderer.render(HiresModelRenderer.java:80) ~[HiresModelRenderer.class:?]
at de.bluecolored.bluemap.core.map.hires.HiresModelManager.render(HiresModelManager.java:72) ~[HiresModelManager.class:?]
at de.bluecolored.bluemap.core.map.BmMap.renderTile(BmMap.java:106) ~[BmMap.class:?]
at de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.doWork(WorldRegionRenderTask.java:118) ~[WorldRegionRenderTask.class:?]
at de.bluecolored.bluemap.common.rendermanager.CombinedRenderTask.doWork(CombinedRenderTask.java:62) ~[CombinedRenderTask.class:?]
at de.bluecolored.bluemap.common.rendermanager.RenderManager.doWork(RenderManager.java:295) ~[RenderManager.class:?]
at de.bluecolored.bluemap.common.rendermanager.RenderManager.access$400(RenderManager.java:35) ~[RenderManager.class:?]
at de.bluecolored.bluemap.common.rendermanager.RenderManager$WorkerThread.run(RenderManager.java:319) [RenderManager$WorkerThread.class:?]
```

it keeped saying forever
### Actual result

i can enter the website however the map is completely dark (i can see my player name)

### Context
**BlueMap Version:**  
BlueMap-1.5.5-sponge-7.2.0

**Comment by TBlueF** [comment]
That error is probably due to a missing `water_still` texture for your water-blocks.. which should never happen.

Is there anything in this folder: `./config/bluemap/resourcepacks/` ?
Also, try to delete `./bluemap/minecraft-client-1.12.0.jar` and reload bluemap :)

**Comment by pys078** [comment]
> That error is probably due to a missing `water_still` texture for your water-blocks.. which should never happen.
> 
> Is there anything in this folder: `./config/bluemap/resourcepacks/` ?
> Also, try to delete `./bluemap/minecraft-client-1.12.0.jar` and reload bluemap :)

there is no resourcepack
but after i deleted the `minecraft-client-1.12.0.jar` it now works perfectly
thank u
