### ISSUE TITLE
Report an error

### ISSUE THREAD

**Issue by Smalltred** [BlueMap-Minecraft/BlueMap#241]
[ERROR] Failed to close file: web\data\nether\hires\x-2\0\z1\5.json.gz
java.nio.file.NoSuchFileException: web\data\nether\hires\x-2\0\z1\5.json.gz.filepart -> web\data\nether\hires\x-2\0\z1\5.json.gz
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:315)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
        at java.base/java.nio.file.Files.move(Files.java:1426)
        at de.bluecolored.bluemap.core.util.AtomicFileHelper.lambda$createFilepartOutputStream$0(AtomicFileHelper.java:46)
        at de.bluecolored.bluemap.core.util.AtomicFileHelper$WrappedOutputStream.close(AtomicFileHelper.java:90)
        at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
        at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:240)
        at de.bluecolored.bluemap.core.map.hires.HiresModelManager.save(HiresModelManager.java:96)
        at de.bluecolored.bluemap.core.map.hires.HiresModelManager.render(HiresModelManager.java:74)
        at de.bluecolored.bluemap.core.map.BmMap.renderTile(BmMap.java:106)
        at de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.doWork(WorldRegionRenderTask.java:118)
        at de.bluecolored.bluemap.common.rendermanager.CombinedRenderTask.doWork(CombinedRenderTask.java:62)
        at de.bluecolored.bluemap.common.rendermanager.RenderManager.doWork(RenderManager.java:295)
        at de.bluecolored.bluemap.common.rendermanager.RenderManager.access$400(RenderManager.java:35)
        at de.bluecolored.bluemap.common.rendermanager.RenderManager$WorkerThread.run(RenderManager.java:319)
[ERROR] Failed to close file: web\data\nether\hires\x-1\9\z1\5.json.gz
java.nio.file.NoSuchFileException: web\data\nether\hires\x-1\9\z1\5.json.gz.filepart -> web\data\nether\hires\x-1\9\z1\5.json.gz
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:315)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
        at java.base/java.nio.file.Files.move(Files.java:1426)
        at de.bluecolored.bluemap.core.util.AtomicFileHelper.lambda$createFilepartOutputStream$0(AtomicFileHelper.java:46)
        at de.bluecolored.bluemap.core.util.AtomicFileHelper$WrappedOutputStream.close(AtomicFileHelper.java:90)
        at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
        at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:240)
        at de.bluecolored.bluemap.core.map.hires.HiresModelManager.save(HiresModelManager.java:96)
        at de.bluecolored.bluemap.core.map.hires.HiresModelManager.render(HiresModelManager.java:74)
        at de.bluecolored.bluemap.core.map.BmMap.renderTile(BmMap.java:106)
        at de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.doWork(WorldRegionRenderTask.java:118)
        at de.bluecolored.bluemap.common.rendermanager.CombinedRenderTask.doWork(CombinedRenderTask.java:62)
        at de.bluecolored.bluemap.common.rendermanager.RenderManager.doWork(RenderManager.java:295)
        at de.bluecolored.bluemap.common.rendermanager.RenderManager.access$400(RenderManager.java:35)
        at de.bluecolored.bluemap.common.rendermanager.RenderManager$WorkerThread.run(RenderManager.java:319)

**Comment by TBlueF** [comment]
Please read the [Conribution Guidlines](https://github.com/BlueMap-Minecraft/BlueMap/blob/master/.github/CONTRIBUTING.md) before opening an issue
