### ISSUE TITLE
server crash after player connection

### ISSUE THREAD

**Issue by PortableGames** [BlueMap-Minecraft/BlueMap#257]
mc 1.18 pre5 fabric bluemap 1.7.0-fabric-1.18

Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'java.io.File net.minecraft.class_2874.method_12488(net.minecraft.class_5321, java.io.File)'
at de.bluecolored.bluemap.fabric.FabricMod.loadUUIDForWorld(FabricMod.java:177) ~[BlueMap-1.7.0-fabric-1.18.jar:?]
at de.bluecolored.shadow.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141) ~[BlueMap-1.7.0-fabric-1.18.jar:?]
at de.bluecolored.shadow.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2344) ~[BlueMap-1.7.0-fabric-1.18.jar:?]
at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
at de.bluecolored.shadow.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342) ~[BlueMap-1.7.0-fabric-1.18.jar:?]
at de.bluecolored.shadow.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325) ~[BlueMap-1.7.0-fabric-1.18.jar:?]
at de.bluecolored.shadow.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[BlueMap-1.7.0-fabric-1.18.jar:?]
at de.bluecolored.shadow.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54) ~[BlueMap-1.7.0-fabric-1.18.jar:?]
at de.bluecolored.bluemap.fabric.FabricMod.getUUIDForWorld(FabricMod.java:166) ~[BlueMap-1.7.0-fabric-1.18.jar:?]
at de.bluecolored.bluemap.fabric.FabricPlayer.update(FabricPlayer.java:143) ~[BlueMap-1.7.0-fabric-1.18.jar:?]
at de.bluecolored.bluemap.fabric.FabricPlayer.<init>(FabricPlayer.java:70) ~[BlueMap-1.7.0-fabric-1.18.jar:?]

**Comment by DeTOB04** [comment]
I'm having the exact same issue here

**Comment by TBlueF** [comment]
Fixed in version 1.7.1
