### ISSUE TITLE
Issue loading Nether and End & loading from mods folder using Magma server!

### ISSUE THREAD

**Issue by TheGreyRaven** [BlueMap-Minecraft/BlueMap#29]
Hello!

First of all I would like to say thank you for creating such an awesome map!
I'm using [Magma](https://github.com/magmafoundation/Magma) (Its a Paper and Forge hybrid).

The issue I'm having is that Magma does not generate a folder for each world, it just has a single world folder.
I noticed this when stopping the server, not sure if it might be useful:
```
[18:58:34] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'world'/overworld
[18:58:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'DIM-1'/the_nether
[18:58:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'DIM1'/the_end`
```

I should also mention that I have your plugin/mod in the plugins folder on the server and not in the mods folder since it does not seem to be loaded when put in the mods folder.

This is the error I get when I have Bluemap in the plugins folder:
```
[19:06:32] [Craft Scheduler Thread - 3/INFO] [de.bluecolored.bluemap.bukkit.BukkitPlugin]: [BlueMap] Loading...
[19:06:37] [Craft Scheduler Thread - 3/ERROR] [de.bluecolored.bluemap.bukkit.BukkitPlugin]: [BlueMap] Failed to load map 'end': '/home/raven/Minecraft/world_the_end' does not exist or is no directory!
java.io.IOException: null
	at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:154) ~[?:?]
	at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78) [CraftTask.class:81086e0]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:81086e0]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [ServerSchedulerReportingWrapper.class:81086e0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[19:06:37] [Craft Scheduler Thread - 3/ERROR] [de.bluecolored.bluemap.bukkit.BukkitPlugin]: [BlueMap] Failed to load map 'nether': '/home/raven/Minecraft/world_nether' does not exist or is no directory!
java.io.IOException: null
	at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:154) ~[?:?]
	at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78) [CraftTask.class:81086e0]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:81086e0]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [ServerSchedulerReportingWrapper.class:81086e0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[19:06:37] [Thread-36/INFO] [de.bluecolored.bluemap.bukkit.BukkitPlugin]: [BlueMap] WebServer started.
```

This is the output I get in the debug log when I have Bluemap in the debug folder:
```
[19:31:40] [main/DEBUG] [FML]: Examining file: BlueMap-0.5.0-mc1.12.jar
[19:31:40] [main/DEBUG] [FML]:   Adding BlueMap-0.5.0-mc1.12.jar to the mod list
[19:31:40] [main/DEBUG] [FML]: Not found coremod data in BlueMap-0.5.0-mc1.12.jar
[19:31:52] [Server thread/DEBUG] [FML]:   Adding BlueMap-0.5.0-mc1.12.jar to the mod list
[19:31:52] [Server thread/DEBUG] [FML]: Found a candidate zip or jar file BlueMap-0.5.0-mc1.12.jar
[19:31:53] [Server thread/DEBUG] [FML]: Examining file BlueMap-0.5.0-mc1.12.jar for potential mods
[19:31:53] [Server thread/TRACE] [FML]: Located mcmod.info file in file BlueMap-0.5.0-mc1.12.jar
[19:31:56] [Server thread/INFO] [FML]: FML has found a non-mod file BlueMap-0.5.0-mc1.12.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
```

Again thank you for creating Bluemap!

**Comment by TBlueF** [comment]
have you tried to change the values in bluemaps config accordingly?
so where you have: `world: "world_nether"` you change it to your dimension-folder `world: "world/DIM-1"`..
That should help :)

Edit: also, bluemap will currently not load from the mods folder, since it does not include a forge-mod implementation, so it has to be loaded as a bukkit plugin ^^

**Comment by TheGreyRaven** [comment]
Ah okay that would make sense, I assumed it would work by placing it in the mods folder since it worked with Sponge Forge's mods folder.

I tested naming it as you shoved and it worked, so thank you!

Another question I have, I do understand that this plugin/mod is in early alpha but I don't know if this might be a know issue that some textures are not correct.
In the nether lava has been replace with Dropper (I think it is) and other block have also been replaced.

I have attached some images that shows the issue, and also some textures are missing from mod blocks.

https://imgur.com/a/VHHfsx4

**Comment by TBlueF** [comment]
So that issue is either your browser cache ... or your `textures.json` is somehow not in sync with your renders ..

First try to view your map in a nother browser or with a disabled cache *(On Chome: F12 -> Network -> Disable Cache)*..

If that didn't work you might need to delete your maps and re-render them again:
Delete the `./bluemap/web/data` folder, and use `/bluemap render <world>` again.
That will fix that issue :)

For mod blocks, please read the wiki: https://github.com/BlueMap-Minecraft/BlueMap/wiki/Configuring-mods
