### ISSUE TITLE
Crash when startup

### ISSUE THREAD

**Issue by kevinmatthe** [BlueMap-Minecraft/BlueMap#291]
### Context
**BlueMap Version:**  
`1.0.0-fabric-1.18.1`

Here is the log:
[12:16:57] [RenderManager-1-0/ERROR]: RenderManager(1): WorkerThread(0): Exception while doing some work!
java.lang.NullPointerException: Cannot invoke "de.bluecolored.bluemap.core.resourcepack.texture.Texture.getId()" because "stillTexture" is null
        at de.bluecolored.bluemap.core.map.hires.blockmodel.LiquidModelBuilder.build(LiquidModelBuilder.java:121) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.core.map.hires.blockmodel.LiquidModelBuilder.build(LiquidModelBuilder.java:93) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.core.map.hires.blockmodel.BlockStateModelFactory.renderModel(BlockStateModelFactory.java:86) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.core.map.hires.blockmodel.BlockStateModelFactory.render(BlockStateModelFactory.java:69) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.core.map.hires.blockmodel.BlockStateModelFactory.render(BlockStateModelFactory.java:58) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.core.map.hires.HiresModelRenderer.render(HiresModelRenderer.java:80) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.core.map.hires.HiresModelManager.render(HiresModelManager.java:66) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.core.map.BmMap.renderTile(BmMap.java:108) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.doWork(WorldRegionRenderTask.java:120) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.CombinedRenderTask.doWork(CombinedRenderTask.java:62) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.RenderManager.doWork(RenderManager.java:296) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.RenderManager.access$400(RenderManager.java:35) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.RenderManager$WorkerThread.run(RenderManager.java:320) [BlueMap-1.7.2-fabric-1.18.jar:?]

**Comment by TBlueF** [comment]
This issue is closed, because it is not conforming our [Contribution-Guidelines](https://github.com/BlueMap-Minecraft/BlueMap/blob/master/.github/CONTRIBUTING.md).
If you need Support, please use our [Discord](https://discord.gg/zmkyJa3).
