### ISSUE TITLE
Error display on website.

### ISSUE THREAD

**Issue by kevinmatthe** [BlueMap-Minecraft/BlueMap#292]
### What i did / Steps to reproduce

I just install this mod, and configure configs, then start my server.
### Expected result

It should be working fine
### Actual result

I can see that the webservice is up, while I can only see a complete black map.
Also, I can see players on website. Just the map is all black.
### Context
**BlueMap Version:**  

`1.7.2-fabric-1.18`

Here is the log output that may help:
```log
[12:16:57] [RenderManager-1-0/ERROR]: RenderManager(1): WorkerThread(0): Exception while doing some work!
java.lang.NullPointerException: Cannot invoke "de.bluecolored.bluemap.core.resourcepack.texture.Texture.getId()" because "stillTexture" is null
at de.bluecolored.bluemap.core.map.hires.blockmodel.LiquidModelBuilder.build(LiquidModelBuilder.java:121) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.core.map.hires.blockmodel.LiquidModelBuilder.build(LiquidModelBuilder.java:93) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.core.map.hires.blockmodel.BlockStateModelFactory.renderModel(BlockStateModelFactory.java:86) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.core.map.hires.blockmodel.BlockStateModelFactory.render(BlockStateModelFactory.java:69) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.core.map.hires.blockmodel.BlockStateModelFactory.render(BlockStateModelFactory.java:58) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.core.map.hires.HiresModelRenderer.render(HiresModelRenderer.java:80) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.core.map.hires.HiresModelManager.render(HiresModelManager.java:66) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.core.map.BmMap.renderTile(BmMap.java:108) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.doWork(WorldRegionRenderTask.java:120) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.common.rendermanager.CombinedRenderTask.doWork(CombinedRenderTask.java:62) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.common.rendermanager.RenderManager.doWork(RenderManager.java:296) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.common.rendermanager.RenderManager.access$400(RenderManager.java:35) ~[BlueMap-1.7.2-fabric-1.18.jar:?]
at de.bluecolored.bluemap.common.rendermanager.RenderManager$WorkerThread.run(RenderManager.java:320) [BlueMap-1.7.2-fabric-1.18.jar:?]
```

**Comment by TBlueF** [comment]
Please delete this file `./bluemap/minecraft-client-?.??.?.jar` and then do `/bluemap reload`, that should fix your issue.

**Comment by kevinmatthe** [comment]
> Please delete this file `./bluemap/minecraft-client-?.??.?.jar` and then do `/bluemap reload`, that should fix your issue.

I will try it, thanks for reply

**Comment by kevinmatthe** [comment]
My server's version is 1.18.1, is it related to this issue?
I deleted the file you mentioned, but still the same (but without the exception log at least):
![image](https://user-images.githubusercontent.com/36391318/154856969-d62340b6-de31-4520-a7b0-66f6a73e4b88.png)
And also, I tried to use updatemap on website, it also fails.
And there's something that may help:
I can't use command like /bluemap purge/debug

**Comment by kevinmatthe** [comment]
Or, does the reload of a map cost very long time? I see it reloading, and when I type `/bluemap`, it says `BlueMap is not loaded, try /bluemap reload`

**Comment by kevinmatthe** [comment]
Alright, after some time it finally load the map successfully.
Thanks for your helpXD
