### ISSUE TITLE
region file not found

### ISSUE THREAD

**Issue by untuned** [BlueMap-Minecraft/BlueMap#30]
![](https://untnd.me/56Qhuda1g)

**Comment by Sciroccogti** [comment]
I also ran into this issue, though I know it might be caused by my copy of the `world/` directory -- because the server is on another computer, I had to copy the files from that one to my current computer.

- platform: Ubuntu 18.04
- Java: openjdk 11.0.6
- Minecraft: 1.15.2, no mod no resource pack

However, it turns out that despite of the error, the map can be rendered correctly. Maybe some of the blocks are not rendered, but it does not matter.

```Java
[DEBUG] Failed to render tile (-503, 463) of map 'world', rescheduling for 2. attempt..[ERROR] Failed to render tile (-504, 463) of map 'world'!
java.io.FileNotFoundException: world/region/r.-32.28.mca (No such file or directory)

        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at de.bluecolored.bluemap.core.mca.MCAWorld.loadChunk(MCAWorld.java:221)
        at de.bluecolored.bluemap.core.mca.MCAWorld.lambda$getChunk$0(MCAWorld.java:204)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
        at de.bluecolored.bluemap.core.mca.MCAWorld.getChunk(MCAWorld.java:204)
        at de.bluecolored.bluemap.core.mca.MCAWorld.isChunkGenerated(MCAWorld.java:256)
        at de.bluecolored.bluemap.core.world.World.isAreaGenerated(World.java:139)
        at de.bluecolored.bluemap.core.world.World.isAreaGenerated(World.java:128)
        at de.bluecolored.bluemap.core.world.World.isAreaGenerated(World.java:119)
        at de.bluecolored.bluemap.core.render.TileRenderer.render(TileRenderer.java:50)
        at de.bluecolored.bluemap.common.MapType.renderTile(MapType.java:72)
        at de.bluecolored.bluemap.common.RenderTicket.render(RenderTicket.java:28)
        at de.bluecolored.bluemap.common.RenderManager.renderThread(RenderManager.java:142)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by TBlueF** [comment]
Related: #24
