### ISSUE TITLE
 Error while starting the WebServer! 

### ISSUE THREAD

**Issue by FrostN0v0** [BlueMap-Minecraft/BlueMap#309]
### What i did / Steps to reproduce
I didn't do anything, but I couldn't start the webserver.The webserver port is not occupied.I tried to change the port, but it still doesn't work.

 Error while starting the WebServer!
java.net.BindException: Cannot assign requested address: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:544) ~[?:?]
	at sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643) ~[?:?]
	at java.net.ServerSocket.bind(ServerSocket.java:388) ~[?:?]
	at java.net.ServerSocket.<init>(ServerSocket.java:274) ~[?:?]
	at de.bluecolored.bluemap.core.webserver.WebServer.start(WebServer.java:75) ~[BlueMap-1.7.3-fabric-1.18.jar:?]
	at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:157) ~[BlueMap-1.7.3-fabric-1.18.jar:?]
	at de.bluecolored.bluemap.fabric.FabricMod.lambda$onInitialize$2(FabricMod.java:107) ~[BlueMap-1.7.3-fabric-1.18.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

### Context
**BlueMap Version:** 
`BlueMap-1.7.3-fabric-1.18`
**MinecraftServer Version:** 
`fabric-server-mc.1.19-loader.0.14.7-launcher.0.11.0`

<!--

**Comment by TBlueF** [comment]
`webserver.conf`

![image](https://user-images.githubusercontent.com/10765470/173577603-8cdb0cc0-21e1-452c-bc9b-b5997e573d6c.png)
;)

If you need more support with this, please join our [discord](https://discord.gg/zmkyJa3). GitHub Issues are not a good place for support :)
