### ISSUE TITLE
Update Fabric Command API v1 -> v2

### ISSUE THREAD

**Issue by syorito-hatsuki** [BlueMap-Minecraft/BlueMap#325]
Minecraft 1.19.2

**Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback**

```java
[23:28:53] [main/ERROR] (Minecraft) Failed to start the minecraft server
 java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bluemap'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.8.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/command/v1/CommandRegistrationCallback
	at de.bluecolored.bluemap.fabric.FabricMod.onInitialize(FabricMod.java:96) ~[bluemap-1.7.3-64b5720b4b825f21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at de.bluecolored.bluemap.fabric.FabricMod.onInitialize(FabricMod.java:96) ~[bluemap-1.7.3-64b5720b4b825f21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	... 7 more
```

**Comment by TBlueF** [comment]
It is updated <https://github.com/BlueMap-Minecraft/BlueMap/blob/master/implementations/fabric-1.19/src/main/java/de/bluecolored/bluemap/fabric/FabricMod.java#L41> in the latest version..

... are you using the correct BlueMap-fabric version?

**Comment by syorito-hatsuki** [comment]
> It is updated https://github.com/BlueMap-Minecraft/BlueMap/blob/master/implementations/fabric-1.19/src/main/java/de/bluecolored/bluemap/fabric/FabricMod.java#L41 in the latest version..
> 
> ... are you using the correct BlueMap-fabric version?

I tried 3.3v. Moment. I try invalidate IDE and resetup from zero

**Comment by TBlueF** [comment]
oh no you are using 1.7.3 still ... yes .. 

This is already implemented in the latest BlueMap Version, then :)

**Comment by TBlueF** [comment]
(`bluemap-1.7.3-64b5720b4b825f21.jar` is what your stacktrace says)

**Comment by syorito-hatsuki** [comment]
> 

F*cking gradle bugs)))
