### ISSUE TITLE
Failed to save settings for map World, Nether, and The End

### ISSUE THREAD

**Issue by Yumileashen** [BlueMap-Minecraft/BlueMap#326]
### What i did / Steps to reproduce
Not Sure, Just running the server for 4 hours

### Expected result
Bluemap Saving setting World, nether, and End

### Actual result
Bluemap failed to save setting

### Context
**BlueMap-3.3-spigot.jar**

Using on windows Paper server with BlueMapOfflineSkinSupport addon

### What i did / Steps to reproduce
Not Sure, Just running the server for 4 hours

### Expected result
Bluemap Saving setting World, nether, and End

### Actual result
Bluemap failed to save setting

### Context
**BlueMap-3.3-spigot.jar**

Using on windows Paper server with BlueMapOfflineSkinSupport addon

[17:20:46 ERROR]: [BlueMap] Failed to save settings for map 'world'!
java.nio.file.AccessDeniedException: bluemap\web\maps\world\settings.json
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275) ~[?:?]
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110) ~[?:?]
        at java.nio.file.Files.deleteIfExists(Files.java:1191) ~[?:?]
        at de.bluecolored.bluemap.core.util.AtomicFileHelper.lambda$createFilepartOutputStream$0(AtomicFileHelper.java:42) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.core.util.WrappedOutputStream.close(WrappedOutputStream.java:71) ~[BlueMap-3.3-spigot.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:347) ~[?:?]
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169) ~[?:?]
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:252) ~[?:?]
        at de.bluecolored.bluemap.core.map.BmMap.saveMapSettings(BmMap.java:193) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.core.map.BmMap.save(BmMap.java:133) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.save(Plugin.java:420) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin$1.run(Plugin.java:244) ~[BlueMap-3.3-spigot.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
        at java.util.TimerThread.run(Timer.java:516) ~[?:?]
[17:20:46 ERROR]: [BlueMap] Failed to save settings for map 'world_the_end'!
java.nio.file.AccessDeniedException: bluemap\web\maps\world_the_end\settings.json
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275) ~[?:?]
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110) ~[?:?]
        at java.nio.file.Files.deleteIfExists(Files.java:1191) ~[?:?]
        at de.bluecolored.bluemap.core.util.AtomicFileHelper.lambda$createFilepartOutputStream$0(AtomicFileHelper.java:42) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.core.util.WrappedOutputStream.close(WrappedOutputStream.java:71) ~[BlueMap-3.3-spigot.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:347) ~[?:?]
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169) ~[?:?]
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:252) ~[?:?]
        at de.bluecolored.bluemap.core.map.BmMap.saveMapSettings(BmMap.java:193) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.core.map.BmMap.save(BmMap.java:133) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.save(Plugin.java:420) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin$1.run(Plugin.java:244) ~[BlueMap-3.3-spigot.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
        at java.util.TimerThread.run(Timer.java:516) ~[?:?]
[17:20:46 ERROR]: [BlueMap] Failed to save settings for map 'world_nether'!
java.nio.file.AccessDeniedException: bluemap\web\maps\world_nether\settings.json
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275) ~[?:?]
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110) ~[?:?]
        at java.nio.file.Files.deleteIfExists(Files.java:1191) ~[?:?]
        at de.bluecolored.bluemap.core.util.AtomicFileHelper.lambda$createFilepartOutputStream$0(AtomicFileHelper.java:42) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.core.util.WrappedOutputStream.close(WrappedOutputStream.java:71) ~[BlueMap-3.3-spigot.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:347) ~[?:?]
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169) ~[?:?]
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:252) ~[?:?]
        at de.bluecolored.bluemap.core.map.BmMap.saveMapSettings(BmMap.java:193) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.core.map.BmMap.save(BmMap.java:133) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.save(Plugin.java:420) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin$1.run(Plugin.java:244) ~[BlueMap-3.3-spigot.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
        at java.util.TimerThread.run(Timer.java:516) ~[?:?]

**Comment by TBlueF** [comment]
This is not a BlueMap Bug, but rather an issue with your Setup.

An access denied exception is some problem with opening/writing to those files on your windows-system. File-Permissions, or the files is/are being used by another process. Make sure you close all other programs accessing those files and make sure your server runs with enough permissions to modify them. 

For more support, please visit our [discord](https://discord.gg/zmkyJa3) :)

**Comment by Yumileashen** [comment]
thank you
