### ISSUE TITLE
Error with loading biomes in 1.12

### ISSUE THREAD

**Issue by TBlueF** [BlueMap-Minecraft/BlueMap#33]
Fixed in 1.13+ chunk-loaders but not in 1.12, apparently this can happen in 1.12 as well:

```
[09:40:58] [Thread-47/ERROR] [bluemap]: Failed to render tile (1, -11) of map 'world'!
java.io.IOException: java.lang.ClassCastException: Cannot cast net.querz.nbt.IntArrayTag to net.querz.nbt.ByteArrayTag
        at de.bluecolored.bluemap.core.mca.MCAWorld.getChunk(MCAWorld.java:213) ~[MCAWorld.class:?]
        at de.bluecolored.bluemap.core.mca.MCAWorld.isChunkGenerated(MCAWorld.java:256) ~[MCAWorld.class:?]
        at de.bluecolored.bluemap.core.world.World.isAreaGenerated(World.java:139) ~[World.class:?]
        at de.bluecolored.bluemap.core.world.World.isAreaGenerated(World.java:128) ~[World.class:?]
        at de.bluecolored.bluemap.core.world.World.isAreaGenerated(World.java:119) ~[World.class:?]
        at de.bluecolored.bluemap.core.render.TileRenderer.render(TileRenderer.java:50) ~[TileRenderer.class:?]
        at de.bluecolored.bluemap.common.MapType.renderTile(MapType.java:72) ~[MapType.class:?]
        at de.bluecolored.bluemap.common.RenderTicket.render(RenderTicket.java:28) ~[RenderTicket.class:?]
        at de.bluecolored.bluemap.common.RenderManager.renderThread(RenderManager.java:142) ~[RenderManager.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassCastException: Cannot cast net.querz.nbt.IntArrayTag to net.querz.nbt.ByteArrayTag
        at java.lang.Class.cast(Class.java:3369) ~[?:1.8.0_242]
        at net.querz.nbt.CompoundTag.get(CompoundTag.java:68) ~[CompoundTag.class:?]
        at net.querz.nbt.CompoundTag.getByteArrayTag(CompoundTag.java:106) ~[CompoundTag.class:?]
        at net.querz.nbt.CompoundTag.getByteArray(CompoundTag.java:166) ~[CompoundTag.class:?]
        at de.bluecolored.bluemap.core.mca.ChunkAnvil112.<init>(ChunkAnvil112.java:65) ~[ChunkAnvil112.class:?]
        at de.bluecolored.bluemap.core.mca.Chunk.create(Chunk.java:77) ~[Chunk.class:?]
        at de.bluecolored.bluemap.core.mca.MCAWorld.loadChunk(MCAWorld.java:247) ~[MCAWorld.class:?]
        at de.bluecolored.bluemap.core.mca.MCAWorld.lambda$getChunk$0(MCAWorld.java:204) ~[MCAWorld.class:?]
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060) ~[minecraft_server.1.12.2.jar:?]
        at de.bluecolored.bluemap.core.mca.MCAWorld.getChunk(MCAWorld.java:204) ~[MCAWorld.class:?]
        ... 9 more
```

**Comment by TBlueF** [comment]
Turns out this was caused by this mod: https://www.curseforge.com/minecraft/mc-mods/jeid
So this is not a bug with bluemap.
