### ISSUE TITLE
PostgreSQL SQL support

### ISSUE THREAD

**Issue by kloenk** [BlueMap-Minecraft/BlueMap#335]
**Is your feature request related to a problem? Please describe.**
Tried setting BlueMap up using PostgreSQL, using the documentation for SQL.

**Describe the solution you'd like**
A sql syntax error is thrown by the PSQL jdbc adapter.

<details>
<summary>Stacktrace</summary>
<pre><code>
################################
 There is a problem with your BlueMap setup!
 Failed to load and initialize the storage 'sql'!
################################
[21:35:18] [Thread-15/ERROR]: Failed to load bluemap!
java.io.IOException: de.bluecolored.bluemap.common.config.ConfigurationException: java.io.IOException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  Position: 28
	at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:326) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.fabric.FabricMod.lambda$onInitialize$2(FabricMod.java:104) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: de.bluecolored.bluemap.common.config.ConfigurationException: java.io.IOException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  Position: 28
	at de.bluecolored.bluemap.common.BlueMapService.getStorage(BlueMapService.java:275) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.common.BlueMapService.loadWorldsAndMaps(BlueMapService.java:214) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.common.BlueMapService.getWorlds(BlueMapService.java:158) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:149) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	... 2 more
Caused by: java.io.IOException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  Position: 28
	at de.bluecolored.bluemap.core.storage.sql.SQLStorage.initialize(SQLStorage.java:477) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.common.BlueMapService.getStorage(BlueMapService.java:273) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.common.BlueMapService.loadWorldsAndMaps(BlueMapService.java:214) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.common.BlueMapService.getWorlds(BlueMapService.java:158) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:149) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	... 2 more
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  Position: 28
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[?:?]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[?:?]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[?:?]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496) ~[?:?]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) ~[?:?]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333) ~[?:?]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319) ~[?:?]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295) ~[?:?]
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:268) ~[?:?]
	at de.bluecolored.shadow.apache.commons.dbcp2.DelegatingStatement.executeUpdate(DelegatingStatement.java:341) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.shadow.apache.commons.dbcp2.DelegatingStatement.executeUpdate(DelegatingStatement.java:341) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.shadow.apache.commons.dbcp2.DelegatingStatement.executeUpdate(DelegatingStatement.java:341) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.core.storage.sql.SQLStorage.lambda$initialize$10(SQLStorage.java:374) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.core.storage.sql.SQLStorage.recoveringConnection(SQLStorage.java:524) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.core.storage.sql.SQLStorage.initialize(SQLStorage.java:373) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.common.BlueMapService.getStorage(BlueMapService.java:273) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.common.BlueMapService.loadWorldsAndMaps(BlueMapService.java:214) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.common.BlueMapService.getWorlds(BlueMapService.java:158) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:149) ~[cvav31clzs97zqn5afbjbr8mjpjbi6k5-BlueMap-3.3-fabric-1.19.jar:?]
	... 2 more
</code></pre>
</details>

I have not enough experience with JDBC to say this is not a JDBC error, but looks like a code feature missing in BlueMap.

**Comment by TBlueF** [comment]
BlueMap currently only supports MySQL-Compatible Databases, so i am treating this as a Feature Request ^^

**Comment by kloenk** [comment]
yeah, meant as Feature request. Used the feature request template, maybe it got lost on GitHub's site.

**Comment by TBlueF** [comment]
Implemented with #443 (f149b823a76e40bbb6532ee6aac467432d6899e9)
