### ISSUE TITLE
Error when joining without accepting downloads

### ISSUE THREAD

**Issue by TBlueF** [BlueMap-Minecraft/BlueMap#338]
Reproduce:
- fresh install bluemap
- don't change any config
- join the server

```
[04:51:25] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to BlueMap v3.4
java.lang.NullPointerException: Cannot invoke "de.bluecolored.bluemap.common.BlueMapService.getWorldId(java.nio.file.Path)" because the return value of "de.bluecolored.bluemap.common.plugin.Plugin.getBlueMap()" is null
	at de.bluecolored.bluemap.bukkit.BukkitPlayer.update(BukkitPlayer.java:165) ~[BlueMap-3.4-spigot.jar:?]
	at de.bluecolored.bluemap.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:67) ~[BlueMap-3.4-spigot.jar:?]
	at de.bluecolored.bluemap.bukkit.BukkitPlugin.onPlayerJoin(BukkitPlugin.java:244) ~[BlueMap-3.4-spigot.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor51.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-"276d830"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[paper-1.18.2.jar:git-Paper-"276d830"]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[paper-1.18.2.jar:git-Paper-"276d830"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:305) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1623) ~[paper-1.18.2.jar:git-Paper-"276d830"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-"276d830"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-"276d830"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-"276d830"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-"276d830"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by TNTUP** [comment]
Lol, I should have reported it but I didn't want to bother you about this :S

**Comment by TBlueF** [comment]
Possibly related: 
```
[BlueMap] Task #24 for BlueMap v3.4 generated an exception
java.lang.NullPointerException: Cannot invoke "de.bluecolored.bluemap.common.BlueMapService.getWorldId(java.nio.file.Path)" because the return value of "de.bluecolored.bluemap.common.plugin.Plugin.getBlueMap()" is null
        at de.bluecolored.bluemap.bukkit.BukkitPlayer.update(BukkitPlayer.java:165) ~[BlueMap-3.4-spigot.jar:?]
        at de.bluecolored.bluemap.bukkit.BukkitPlugin.updateSomePlayers(BukkitPlugin.java:284) ~[BlueMap-3.4-spigot.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-177]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-177]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
