### ISSUE TITLE
Cannot invoke "com.earth2me.essentials.User.getHomes()" because "user" is null

### ISSUE THREAD

**Issue by candy999** [BlueMap-Minecraft/BlueMap#373]
### Expected result

[10:17:06 INFO]: [BlueMap] Baking resources...
[10:17:06 INFO]: [BlueMap] Resources loaded.
[10:17:06 INFO]: [BlueMap] Initializing Storage: 'file' (Type: FILE)
[10:17:06 INFO]: [BlueMap] WebServer bound to: 0.0.0.0/0.0.0.0:8123
[10:17:06 INFO]: [BlueMap] WebServer started.
[10:17:10 INFO]: [BlueMap] Loaded!
### Actual result

[10:17:06 INFO]: [BlueMap] Baking resources...
[10:17:06 INFO]: [BlueMap] Resources loaded.
[10:17:06 INFO]: [BlueMap] Initializing Storage: 'file' (Type: FILE)
[10:17:06 INFO]: [BlueMap] WebServer bound to: 0.0.0.0/0.0.0.0:8123
[10:17:06 INFO]: [BlueMap] WebServer started.
[10:17:10 ERROR]: [BlueMap] BlueMapAPI: A BlueMapAPI listener threw an exception (onEnable)!
java.lang.NullPointerException: Cannot invoke "com.earth2me.essentials.User.getHomes()" because "user" is null
        at org.popcraft.bluemapessentials.BlueMapEssentials.addHomeMarkers(BlueMapEssentials.java:140) ~[BlueMap-Essentials.jar:?]
        at org.popcraft.bluemapessentials.BlueMapEssentials.addMarkers(BlueMapEssentials.java:91) ~[BlueMap-Essentials.jar:?]
        at org.popcraft.bluemapessentials.BlueMapEssentials.lambda$onEnable$0(BlueMapEssentials.java:50) ~[BlueMap-Essentials.jar:?]
        at de.bluecolored.bluemap.api.BlueMapAPI.registerInstance(BlueMapAPI.java:201) ~[BlueMap.jar:?]
        at de.bluecolored.bluemap.common.api.BlueMapAPIImpl.register(BlueMapAPIImpl.java:137) ~[BlueMap.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:319) ~[BlueMap.jar:?]
        at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:147) ~[BlueMap.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:17:10 INFO]: [BlueMap] Loaded!
### Context
**BlueMap Version:**  
`BlueMap 3.7`
`BlueMap-Essentials 1.1.0`
`Current: git-Purpur-1861 (MC: 1.19.3)*`
`EssentialsX  2.20.0-dev+20-582a357 (build 1441, commit 582a357)`

**Comment by Chicken** [comment]
Not an issue with BlueMap. Raise an issue over at the [BlueMap-Essentials](https://github.com/pop4959/BlueMap-Essentials) repository.
