### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by kentonc04** [BlueMap-Minecraft/BlueMap#385]
I try to start up my server and I'm unable to

###
bluemap 3.9

Raspberry pi B4 8GB headless Debian Linux 11 spigot default world settings
###

[22:56:04] [Craft Scheduler Thread - 0/INFO]: [BlueMap] Loading resources...
[22:56:09] [Craft Scheduler Thread - 0/INFO]: [BlueMap] Loading textures...
[22:56:13] [Craft Scheduler Thread - 0/INFO]: [BlueMap] Baking resources...
[22:56:13] [Craft Scheduler Thread - 0/INFO]: [BlueMap] Resources loaded.
[22:56:13] [Craft Scheduler Thread - 0/INFO]: [BlueMap] Initializing Storage: 'file' (Type: FILE)
[22:56:14] [Craft Scheduler Thread - 0/ERROR]: [BlueMap] Error while starting the WebServer!
java.net.BindException: Permission denied
        at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
        at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
        at sun.nio.ch.Net.bind(Net.java:544) ~[?:?]
        at sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:640) ~[?:?]
        at java.net.ServerSocket.bind(ServerSocket.java:392) ~[?:?]
        at java.net.ServerSocket.<init>(ServerSocket.java:274) ~[?:?]
        at de.bluecolored.bluemap.common.webserver.WebServer.start(WebServer.java:72) ~[?:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:202) ~[?:?]
        at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:147) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:56:14] [Craft Scheduler Thread - 0/INFO]: [BlueMap] Loaded!

**Comment by TBlueF** [comment]
This happens if your JVM does - for some reason - not have permission to use the port that the webserver wants to bind to. (the one configured in `websever.conf`).

This is not a bug with BlueMap, so GitHub is the wrong place to discuss this. *(See the [Contributing Guidelines](https://github.com/BlueMap-Minecraft/BlueMap/blob/b454d15264ce266b571f77f18e5d889b80c15f09/.github/CONTRIBUTING.md))*

**If you need support, please visit our [Discord](https://discord.gg/zmkyJa3) :)**
