### ISSUE TITLE
Markers does not work anymore

### ISSUE THREAD

**Issue by loranger** [BlueMap-Minecraft/BlueMap#403]
Hi,

I use bluemap 3.12 on a papermc server, but I cannot have any marker for few versions now (I can't remember when it stopped working).

Here is the error output I got:

```
[15:22:26 INFO]: [Plugin] [MCGBME] The Bluemap API is loading...
[15:22:26 ERROR]: [BlueMap] BlueMapAPI: A BlueMapAPI listener threw an exception (onEnable)!
java.lang.NoSuchMethodError: 'de.bluecolored.bluemap.api.marker.MarkerAPI de.bluecolored.bluemap.api.BlueMapAPI.getMarkerAPI()'
	at com.mmuziek.BME.BMECore.lambda$onEnable$0(BMECore.java:104) ~[MCGBluemapEssentials.jar:?]
	at de.bluecolored.bluemap.api.BlueMapAPI.registerInstance(BlueMapAPI.java:209) ~[BlueMap-3.12-spigot.jar:?]
	at de.bluecolored.bluemap.common.api.BlueMapAPIImpl.register(BlueMapAPIImpl.java:166) ~[BlueMap-3.12-spigot.jar:?]
	at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:322) ~[BlueMap-3.12-spigot.jar:?]
	at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:105) ~[BlueMap-3.12-spigot.jar:?]
	at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:147) ~[BlueMap-3.12-spigot.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-466]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-466]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:22:26 INFO]: [BlueMap] Loaded!
```

Except the markers, other bluemap features works flawlessly.
How can I fix this ?

**Comment by Chicken** [comment]
MCG BlueMap Essentials doesn't support newer versions of BlueMap

**Comment by TBlueF** [comment]
This is an error with a BlueMap Addon, which uses an outdated API Version.
Closing :)

For support, please visit us on our [discord](https://discord.gg/zmkyJa3), thank you! :)
