### ISSUE TITLE
Error While Running Bluemap Purge Command

### ISSUE THREAD

**Issue by tropicthedev** [BlueMap-Minecraft/BlueMap#419]
### What i did / Steps to reproduce

Run the /bluemap purge

### Expected result

The purge command to execute and delete the world
### Actual result

We got an error message
```
[ WARN] (RenderManager-0-0) Error: 1109-42S02: Unknown table 't' in MULTI DELETE
[00:41:48] [RenderManager-0-0/ERROR]: RenderManager(0): WorkerThread(0): Exception while doing some work!
java.io.IOException: java.sql.SQLSyntaxErrorException: (conn=5099464) Unknown table 't' in MULTI DELETE
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage.purgeMap(SQLStorage.java:408) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.MapPurgeTask.doWork(MapPurgeTask.java:59) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.RenderManager.doWork(RenderManager.java:296) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.RenderManager$WorkerThread.run(RenderManager.java:320) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
Caused by: java.sql.SQLSyntaxErrorException: (conn=5099464) Unknown table 't' in MULTI DELETE
        at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:280) ~[?:?]
        at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368) ~[?:?]
        at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137) ~[?:?]
        at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:833) ~[?:?]
        at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:772) ~[?:?]
        at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:691) ~[?:?]
        at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:634) ~[?:?]
        at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:95) ~[?:?]
        at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:334) ~[?:?]
        at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:311) ~[?:?]
        at de.bluecolored.shadow.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.shadow.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.shadow.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage.executeUpdate(SQLStorage.java:608) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage.lambda$purgeMap$10(SQLStorage.java:400) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage$ConnectionConsumer.apply(SQLStorage.java:768) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage$ConnectionConsumer.apply(SQLStorage.java:761) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage.recoveringConnection(SQLStorage.java:624) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage.recoveringConnection(SQLStorage.java:613) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage.purgeMap(SQLStorage.java:381) ~[BlueMap-3.12-fabric-1.19.4.jar:?]
        ... 3 more```
### Context
**BlueMap Version:** <!-- Full BlueMap-version including the target, for example: --> 
`1.0.0-fabric-1.16.1`
Bluemap 3.12 Fabric

<!-- 
Add more context here!
- The used os and platform (Windows/Linux, Spigot/Paper/Forge/Fabric/Sponge)
- Has the world been generated using any minecraft-mods?
etc..

Also:
- Is there a log- or a config-file that might help? Include it.
- Maybe add a screenshot or video for illustration.
-->

Hosted On Oracle Cloud Infra
Arm 4 Core With 24 GB of RAM Ubuntu Server

**Comment by Chicken** [comment]
Update BlueMap, this has been fixed.

**Comment by tropicthedev** [comment]
Thank you
