### ISSUE TITLE
BlueMap threading error (stacktrace)

### ISSUE THREAD

**Issue by sofianedjerbi** [BlueMap-Minecraft/BlueMap#428]
### What i did / Steps to reproduce
It happens randomly on player login.

### Expected result
No stacktrace.

### Actual result
Stacktrace:
```
[23:55:00 ERROR]: Could not pass event PlayerQuitEvent to BlueMap v3.13-13-dirty
java.util.ConcurrentModificationException: null
        at java.util.ArrayList.removeIf(ArrayList.java:1695) ~[?:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
        at de.bluecolored.bluemap.bukkit.BukkitPlugin.onPlayerLeave(BukkitPlugin.java:254) ~[BlueMap-3.13-13-dirty-folia.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor20.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[kaiiju-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[kaiiju-api-1.19.4-R0.1-SNAPSHOT.jar:git-Kaiiju-"57bd665"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[kaiiju-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[kaiiju-1.19.4.jar:git-Kaiiju-"57bd665"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[kaiiju-1.19.4.jar:git-Kaiiju-"57bd665"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[kaiiju-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:663) ~[kaiiju-1.19.4.jar:git-Kaiiju-"57bd665"]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:648) ~[kaiiju-1.19.4.jar:git-Kaiiju-"57bd665"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2153) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2132) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:836) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:462) ~[kaiiju-1.19.4.jar:git-Kaiiju-"57bd665"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1537) ~[kaiiju-1.19.4.jar:git-Kaiiju-"57bd665"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.19.4.jar:git-Kaiiju-"57bd665"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.19.4.jar:git-Kaiiju-"57bd665"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.19.4.jar:git-Kaiiju-"57bd665"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Context
**BlueMap Version:**  
`git-Kaiiju-"57bd665"` (Folia)
`BlueMap v3.13-13-dirty` (Bluemap)

**Comment by TBlueF** [comment]
I tried to fix this with this commit: c5c791bd0d3e1cdbb6c3a88acd735223694f4574
Please tell me if this error persists or if you think there is a better solution :)
