### ISSUE TITLE
ArithmeticException by trying to normalize the zero vector

### ISSUE THREAD

**Issue by Mordna** [BlueMap-Minecraft/BlueMap#43]
An ArithmeticException is sometimes triggered (on rendering the End) and results in an uncaughtException in the ThreadGroup.
```
java.lang.ArithmeticException: Cannot normalize the zero vector
        at com.flowpowered.math.vector.Vector3f.normalize(Vector3f.java:294)
        at de.bluecolored.bluemap.core.util.MathUtils.getSurfaceNormal(MathUtils.java:70)
        at de.bluecolored.bluemap.core.model.Face.getFaceNormal(Face.java:205)
        at de.bluecolored.bluemap.core.model.Face.<init>(Face.java:54)
        at de.bluecolored.bluemap.core.model.ExtendedFace.<init>(ExtendedFace.java:45)
        at de.bluecolored.bluemap.core.render.hires.blockmodel.ResourceModelBuilder.createElementFace(ResourceModelBuilder.java:192)
        at de.bluecolored.bluemap.core.render.hires.blockmodel.ResourceModelBuilder.fromModelElementResource(ResourceModelBuilder.java:104)
        at de.bluecolored.bluemap.core.render.hires.blockmodel.ResourceModelBuilder.build(ResourceModelBuilder.java:70)
        at de.bluecolored.bluemap.core.render.hires.blockmodel.BlockStateModelFactory.createModel(BlockStateModelFactory.java:85)
        at de.bluecolored.bluemap.core.render.hires.blockmodel.BlockStateModelFactory.createFrom(BlockStateModelFactory.java:61)
        at de.bluecolored.bluemap.core.render.hires.blockmodel.BlockStateModelFactory.createFrom(BlockStateModelFactory.java:47)
        at de.bluecolored.bluemap.core.render.hires.HiresModelRenderer.render(HiresModelRenderer.java:78)
        at de.bluecolored.bluemap.core.render.hires.HiresModelManager.render(HiresModelManager.java:79)
        at de.bluecolored.bluemap.core.render.TileRenderer.render(TileRenderer.java:52)
        at de.bluecolored.bluemap.common.MapType.renderTile(MapType.java:72)
        at de.bluecolored.bluemap.common.RenderTicket.render(RenderTicket.java:52)
        at de.bluecolored.bluemap.common.RenderManager.renderThread(RenderManager.java:165)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by take-my-evolution** [comment]
I get this error when using  ultra_amplified_mod-1.12.2-4.6.2
