### ISSUE TITLE
Minecraft Version 1.20 Bluemap 3.14 Fabric 0.14.21

### ISSUE THREAD

**Issue by slitterell** [BlueMap-Minecraft/BlueMap#439]
### What i did / Steps to reproduce
Installed Fabric version 0.14.21 (Latest) with installer "fabric-server-mc.1.20-loader.0.14.21-launcher.0.11.2.jar"
Put "BlueMap-3.14-fabric-1.20.jar" in the mods folder

### Expected result
It to load MC with  Bluemap

### Actual result
[14:16:52] [main/INFO]: Loading Minecraft 1.20 with Fabric Loader 0.14.21
[14:16:53] [main/WARN]: Mod resolution failed
[14:16:53] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE bluemap 3.14 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE bluemap 3.14]
[14:16:53] [main/INFO]: Reason: [HARD_DEP bluemap 3.14 {depends fabric @ [*]}, HARD_DEP bluemap 3.14 {depends fabric-api-base @ [*]}]
[14:16:53] [main/INFO]: Fix: add [add:fabric 1 ([(-∞,∞)]), add:fabric-api-base 1 ([(-∞,∞)])], remove [], replace []
[14:16:53] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install fabric, any version.
         - Install fabric-api-base, any version.
Unmet dependency listing:
         - Mod 'BlueMap' (bluemap) 3.14 requires any version of fabric, which is missing!
         - Mod 'BlueMap' (bluemap) 3.14 requires any version of fabric-api-base, which is missing!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]

### Context
Included above
Vanilla other than Bluemap. 
Ubuntu

Otherwise, the server loads fine without Bluemap and is playable on Fabric

**Comment by Chicken** [comment]
Seems like you are missing the fabric api mod

**Comment by TBlueF** [comment]
What Chicken said..
BlueMap Fabric depends on [Fabric API](https://modrinth.com/mod/fabric-api) which you also need to install :)

**Comment by slitterell** [comment]
yeah...damn it. Newer to modded MC. I don't understand why that isn't included when you dl fabric
