### ISSUE TITLE
Marker config produces weird error

### ISSUE THREAD

**Issue by TBlueF** [BlueMap-Minecraft/BlueMap#458]
Using this marker config:
```hocon
marker-sets: {

  # Please check out the wiki for information on how to configure this:
  # https://bluemap.bluecolored.de/wiki/customization/Markers.html
    WorldBorder-set: {
        label: "WorldBorder"
        toggleable: true
        default-hidden: false
        sorting: 0
        markers: {
            WorldBorder-marker: {
                type: "line"
                position: { x: 200, y: 64, z: -200 }
                label: "Bordure du monde"
                line: [
                    { x: 200, y: 64, z: -200 }
                    { x: 200, y: 64, z: 200 }
                    { x: -200, y: 64, z: 200 }
                    { x: -200, y: 64, z: -200 }
                    { x: 200, y: 64, z: -200 }
                ]

                # Optional:
                link: null
                new-tab: false
                depth-test: false
                line-width: 5
                line-color: { r: 255, g: 0, b: 0, a: 1.0 }
                sorting: 0
                listed: true
                min-distance: 10
                max-distance: 10000000
            }
        }
    }
}
```

Results in this error:
```
[23:41:44 ERROR]: [BlueMap] Detailed error:
de.bluecolored.bluemap.common.config.ConfigurationException: de.bluecolored.shadow.configurate.ConfigurateException: [WorldBorder-set, markers, WorldBorder-marker, type]: java.lang.IllegalStateException
        at de.bluecolored.bluemap.common.BlueMapService.loadMapConfig(BlueMapService.java:287) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.common.BlueMapService.loadWorldsAndMaps(BlueMapService.java:198) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.common.BlueMapService.getWorlds(BlueMapService.java:183) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:171) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:112) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.reload(Plugin.java:465) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.commands.Commands.lambda$reloadCommand$5(Commands.java:398) ~[BlueMap-3.16-spigot.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: de.bluecolored.shadow.configurate.ConfigurateException: [WorldBorder-set, markers, WorldBorder-marker, type]: java.lang.IllegalStateException
        at de.bluecolored.shadow.configurate.gson.GsonVisitor.enterNode(GsonVisitor.java:65) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.gson.GsonVisitor.enterNode(GsonVisitor.java:30) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.AbstractConfigurationNode.visitInternal(AbstractConfigurationNode.java:666) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.AbstractConfigurationNode.visit(AbstractConfigurationNode.java:637) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.gson.GsonConfigurationLoader.saveInternal(GsonConfigurationLoader.java:313) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:201) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.loader.AbstractConfigurationLoader$Builder.buildAndSaveString(AbstractConfigurationLoader.java:476) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.common.BlueMapService.loadMapConfig(BlueMapService.java:277) ~[BlueMap-3.16-spigot.jar:?]
        ... 7 more
        Suppressed: java.io.IOException: Incomplete document
                at com.google.gson.stream.JsonWriter.close(JsonWriter.java:610) ~[gson-2.10.jar:?]
                at de.bluecolored.shadow.configurate.gson.GsonConfigurationLoader.saveInternal(GsonConfigurationLoader.java:310) ~[BlueMap-3.16-spigot.jar:?]
                at de.bluecolored.shadow.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:201) ~[BlueMap-3.16-spigot.jar:?]
                at de.bluecolored.shadow.configurate.loader.AbstractConfigurationLoader$Builder.buildAndSaveString(AbstractConfigurationLoader.java:476) ~[BlueMap-3.16-spigot.jar:?]
                at de.bluecolored.bluemap.common.BlueMapService.loadMapConfig(BlueMapService.java:277) ~[BlueMap-3.16-spigot.jar:?]
                at de.bluecolored.bluemap.common.BlueMapService.loadWorldsAndMaps(BlueMapService.java:198) ~[BlueMap-3.16-spigot.jar:?]
                at de.bluecolored.bluemap.common.BlueMapService.getWorlds(BlueMapService.java:183) ~[BlueMap-3.16-spigot.jar:?]
                at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:171) ~[BlueMap-3.16-spigot.jar:?]
                at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:112) ~[BlueMap-3.16-spigot.jar:?]
                at de.bluecolored.bluemap.common.plugin.Plugin.reload(Plugin.java:465) ~[BlueMap-3.16-spigot.jar:?]
                at de.bluecolored.bluemap.common.plugin.commands.Commands.lambda$reloadCommand$5(Commands.java:398) ~[BlueMap-3.16-spigot.jar:?]
                at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException
        at com.google.gson.stream.JsonWriter.name(JsonWriter.java:390) ~[gson-2.10.jar:?]
        at de.bluecolored.shadow.configurate.gson.GsonVisitor.enterNode(GsonVisitor.java:63) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.gson.GsonVisitor.enterNode(GsonVisitor.java:30) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.AbstractConfigurationNode.visitInternal(AbstractConfigurationNode.java:666) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.AbstractConfigurationNode.visit(AbstractConfigurationNode.java:637) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.gson.GsonConfigurationLoader.saveInternal(GsonConfigurationLoader.java:313) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:201) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.shadow.configurate.loader.AbstractConfigurationLoader$Builder.buildAndSaveString(AbstractConfigurationLoader.java:476) ~[BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.common.BlueMapService.loadMapConfig(BlueMapService.java:277) ~[BlueMap-3.16-spigot.jar:?]
        ... 7 more
```

**Comment by TBlueF** [comment]
This seems to be a bug in the Configurate Library. For BlueMap this is a `won't-fix` for now. The fix is to just not use any `null` values in the marker-config as you can alternatively just comment-out the whole key:value pair :)

The wiki has been updated accordingly.
