### ISSUE TITLE
Error rendering map

### ISSUE THREAD

**Issue by PixelRave** [BlueMap-Minecraft/BlueMap#489]
### What i did / Steps to reproduce
Started the program trough command line as shown below

### Expected result
Render the map with no errors

### Actual result
Exception error as listed bellow in console readout

### Context
BlueMap-3.17-cli.jar

Running as CLI / standalone

- Linux - Fedora
- openjdk version "17.0.8" 2023-07-18
-  Save location... `/home/ben/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Survival/.minecraft/saves/Mésis`

I have followed all the directions on the installation page. And have also done the following applied the correct location of the save folder. I am not sure what is causing this error..

Console Output...

```
[ben@ben-pc mc]$ java -jar BlueMap-3.17-cli.jar -r
[00:35:26 INFO] Loading resources...
[00:35:26 INFO] Loading textures...
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
	at de.bluecolored.bluemap.core.resources.resourcepack.ResourcePack.lambda$loadTextures$40(ResourcePack.java:377)
	at de.bluecolored.bluemap.core.resources.resourcepack.ResourcePack.loadResource(ResourcePack.java:426)
	at de.bluecolored.bluemap.core.resources.resourcepack.ResourcePack.lambda$loadTextures$41(ResourcePack.java:372)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at de.bluecolored.bluemap.core.resources.resourcepack.ResourcePack.loadTextures(ResourcePack.java:372)
	at de.bluecolored.bluemap.core.resources.resourcepack.ResourcePack.loadResourcePath(ResourcePack.java:236)
	at de.bluecolored.bluemap.core.resources.resourcepack.ResourcePack.loadResourcePath(ResourcePack.java:212)
	at de.bluecolored.bluemap.core.resources.resourcepack.ResourcePack.loadResources(ResourcePack.java:197)
	at de.bluecolored.bluemap.common.BlueMapService.getResourcePack(BlueMapService.java:428)
	at de.bluecolored.bluemap.cli.BlueMapCLI.renderMaps(BlueMapCLI.java:82)
	at de.bluecolored.bluemap.cli.BlueMapCLI.main(BlueMapCLI.java:365)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-17.0.8.0.7-1.fc38.x86_64/lib/libawt_xawt.so [in thread "BlueMap-FJP-0"]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
	at java.desktop/sun.awt.AppContext$2.run(AppContext.java:273)
	at java.desktop/sun.awt.AppContext$2.run(AppContext.java:262)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/sun.awt.AppContext.initMainAppContext(AppContext.java:262)
	at java.desktop/sun.awt.AppContext$3.run(AppContext.java:315)
	at java.desktop/sun.awt.AppContext$3.run(AppContext.java:298)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/sun.awt.AppContext.getAppContext(AppContext.java:297)
	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:129)
	at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at de.bluecolored.bluemap.core.resources.resourcepack.ResourcePack.lambda$loadResources$17(ResourcePack.java:282)
	at de.bluecolored.bluemap.core.resources.resourcepack.ResourcePack.loadResource(ResourcePack.java:426)
	at de.bluecolored.bluemap.core.resources.resourcepack.ResourcePack.lambda$loadResources$18(ResourcePack.java:280)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at de.bluecolored.bluemap.core.resources.resourcepack.ResourcePack.lambda$loadResources$19(ResourcePack.java:280)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by TBlueF** [comment]
Looks like your Java-Installation is missing a library, did you maybe install the headless version of java on your server?

Try re-installing java and make sure to install the normal full java-version :)

**Comment by PixelRave** [comment]
> Looks like your Java-Installation is missing a library, did you maybe install the headless version of java on your server?
> 
> Try re-installing java and make sure to install the normal full java-version :)

Hello thank you for the quick reply! This not running on a server of any sort. Just running trough the console. Do you happen to know what library I am missing? Maybe I can install it?

**Comment by TBlueF** [comment]
`Can't load library: /usr/lib/jvm/java-17-openjdk-17.0.8.0.7-1.fc38.x86_64/lib/libawt_xawt.so`
The library should usually come with your openjdk installation. Unless you installed the headless version.

As this is now going more into support and i am confident that this is not a problem on bluemap's end, I'll close this issue.
If you need further support with this, please use our [support-discord](https://discord.gg/zmkyJa3). GitHub is not a very good place for support :)

**Comment by PixelRave** [comment]
I found that installing this mod with fabric works just fine for my case.
