### ISSUE TITLE
Failed to load and initialize the storage 'sql'

### ISSUE THREAD

**Issue by kotori2** [BlueMap-Minecraft/BlueMap#510]
### What i did / Steps to reproduce
1. Install Fabric server 1.20.4.
2. Install `BlueMap-3.20-fabric-1.20.jar` to mods.
3. Launch server, accept EULA.
4. Set storage of overworld to `sql`.
5. Restart service.

### Expected result
Storage engine loaded as SQL

### Actual result
```
[18:33:04] [BlueMap-Plugin-Loading/INFO]: Initializing Storage: 'sql' (Type: SQL)
[18:33:04] [BlueMap-Plugin-Loading/WARN]:
################################
 There is a problem with your BlueMap setup!
 Failed to load and initialize the storage 'sql'!
################################
[18:33:04] [BlueMap-Plugin-Loading/ERROR]: Failed to load bluemap!
java.io.IOException: de.bluecolored.bluemap.common.config.ConfigurationException: java.io.IOException: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/bluemap?permitMysqlScheme
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:369) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:112) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.fabric.FabricMod.lambda$onInitialize$2(FabricMod.java:104) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: de.bluecolored.bluemap.common.config.ConfigurationException: java.io.IOException: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/bluemap?permitMysqlScheme
        at de.bluecolored.bluemap.common.BlueMapService.getStorage(BlueMapService.java:312) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:194) ~[BlueMap-3.20-fabric-1.20.jar:?]
        ... 3 more
Caused by: java.io.IOException: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/bluemap?permitMysqlScheme
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage.initialize(SQLStorage.java:489) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.common.BlueMapService.getStorage(BlueMapService.java:310) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:194) ~[BlueMap-3.20-fabric-1.20.jar:?]
        ... 3 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/bluemap?permitMysqlScheme
        at java.sql.DriverManager.getConnection(DriverManager.java:706) ~[java.sql:?]
        at java.sql.DriverManager.getConnection(DriverManager.java:190) ~[java.sql:?]
        at de.bluecolored.shadow.apache.commons.dbcp2.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:123) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage.lambda$createDataSource$16(SQLStorage.java:651) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.shadow.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:374) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.shadow.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.shadow.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.shadow.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.shadow.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.shadow.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:141) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage.recoveringConnection(SQLStorage.java:539) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.core.storage.sql.SQLStorage.initialize(SQLStorage.java:389) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.common.BlueMapService.getStorage(BlueMapService.java:310) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:194) ~[BlueMap-3.20-fabric-1.20.jar:?]
        ... 3 more
```

### Context
**BlueMap Version:**  
`BlueMap-3.20-fabric-1.20`

Additionally, mysql connector is not in the libraries.

**Comment by TBlueF** [comment]
BlueMap is not providing a mysql driver, and fabric isn't either. Instead you'll have to provide one yourself.
See: https://bluemap.bluecolored.de/wiki/customization/Storages.html#mysql-mariadb--postgres
and: https://modrinth.com/plugin/mysql-jdbc
