### ISSUE TITLE
[4.1] `BlueMap-Plugin-UpdateCommand failed main thread check: world save` exception after `bluemap update world` console command

### ISSUE THREAD

**Issue by globau** [BlueMap-Minecraft/BlueMap#528]
### What i did / Steps to reproduce

1. brand new server and world
2. `bluemap update world` on console

### Expected result

- bluemap should have updated its map

### Actual result

```
> bluemap update world
[04:46:30 ERROR]: Thread BlueMap-Plugin-UpdateCommand failed main thread check: world save
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[paper-1.20.4.jar:git-Paper-463]
	at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.save(CraftWorld.java:1296) ~[paper-1.20.4.jar:git-Paper-463]
	at de.bluecolored.bluemap.bukkit.BukkitWorld.persistWorldChanges(BukkitWorld.java:74) ~[BlueMap.jar:?]
	at de.bluecolored.bluemap.common.plugin.Plugin.flushWorldUpdates(Plugin.java:573) ~[BlueMap.jar:?]
	at de.bluecolored.bluemap.common.plugin.commands.Commands.lambda$updateCommand$16(Commands.java:742) ~[BlueMap.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[04:46:30 WARN]: Exception in thread "BlueMap-Plugin-UpdateCommand" java.lang.IllegalStateException: Asynchronous world save!
[04:46:30 WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[04:46:30 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.save(CraftWorld.java:1296)
[04:46:30 WARN]: 	at BlueMap.jar//de.bluecolored.bluemap.bukkit.BukkitWorld.persistWorldChanges(BukkitWorld.java:74)
[04:46:30 WARN]: 	at BlueMap.jar//de.bluecolored.bluemap.common.plugin.Plugin.flushWorldUpdates(Plugin.java:573)
[04:46:30 WARN]: 	at BlueMap.jar//de.bluecolored.bluemap.common.plugin.commands.Commands.lambda$updateCommand$16(Commands.java:742)
[04:46:30 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

The map was updated in spite of this error (I assume an update was already in progress).

### Context
`BlueMap-4.1-paper`
`Paper-1.20.4-b463`

**Comment by Teense** [comment]
Same there, quite annoying.

**Comment by TBlueF** [comment]
a0e91803608050f1014c43a9d27492348c10393d fixed this already, will be fixed in next release :)
