### ISSUE TITLE
string index out of bounds error on load of sponge plugin

### ISSUE THREAD

**Issue by IronworksProductions** [BlueMap-Minecraft/BlueMap#53]
Hey, I am getting this error on the load of the sponge plugin:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
at java.lang.String.charAt(String.java:658) ~[?:1.8.0_162]
at de.bluecolored.bluemap.core.resourcepack.BlockModelResource$Builder.getTexture(BlockModelResource.java:431) ~[BlockModelResource$Builder.class:?]
at de.bluecolored.bluemap.core.resourcepack.BlockModelResource$Builder.getTexture(BlockModelResource.java:434) ~[BlockModelResource$Builder.class:?]
at de.bluecolored.bluemap.core.resourcepack.BlockModelResource$Builder.buildNoReset(BlockModelResource.java:306) ~[BlockModelResource$Builder.class:?]
at de.bluecolored.bluemap.core.resourcepack.BlockModelResource$Builder.buildNoReset(BlockModelResource.java:287) ~[BlockModelResource$Builder.class:?]
at de.bluecolored.bluemap.core.resourcepack.BlockModelResource$Builder.buildNoReset(BlockModelResource.java:287) ~[BlockModelResource$Builder.class:?]
at de.bluecolored.bluemap.core.resourcepack.BlockModelResource$Builder.build(BlockModelResource.java:258) ~[BlockModelResource$Builder.class:?]
at de.bluecolored.bluemap.core.resourcepack.BlockStateResource$Builder.loadModel(BlockStateResource.java:255) ~[BlockStateResource$Builder.class:?]
at de.bluecolored.bluemap.core.resourcepack.BlockStateResource$Builder.loadModels(BlockStateResource.java:235) ~[BlockStateResource$Builder.class:?]
at de.bluecolored.bluemap.core.resourcepack.BlockStateResource$Builder.buildForge(BlockStateResource.java:401) ~[BlockStateResource$Builder.class:?]
at de.bluecolored.bluemap.core.resourcepack.BlockStateResource$Builder.build(BlockStateResource.java:171) ~[BlockStateResource$Builder.class:?]
at de.bluecolored.bluemap.core.resourcepack.ResourcePack.load(ResourcePack.java:160) ~[ResourcePack.class:?]
at de.bluecolored.bluemap.core.resourcepack.ResourcePack.load(ResourcePack.java:123) ~[ResourcePack.class:?]
at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:165) ~[Plugin.class:?]
at de.bluecolored.bluemap.sponge.SpongePlugin.lambda$onServerStart$0(SpongePlugin.java:100) ~[SpongePlugin.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.2.1]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.2.1]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```
Any idea what is causing it?

**Comment by TBlueF** [comment]
Some blockmodel of the resources in bluemaps resourcepack folder has an empty-string as a texture-definition i guess..
That's a malformatted resource, but should still not cause an error in bluemap (but a warning)
