### ISSUE TITLE
async update does not work

### ISSUE THREAD

**Issue by KaBoom13** [BlueMap-Minecraft/BlueMap#534]
### What i did / Steps to reproduce
1. run the server and bluemap on it
2. execute /bluemap force-update world or bluemap update world
3. end

### Expected result
start update world

### Actual result
displays an error:
> bluemap force-update world
[17:00:01 ERROR]: Thread BlueMap-Plugin-UpdateCommand failed main thread check: world save
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[paper-1.20.4.jar:git-Paper-485]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.save(CraftWorld.java:1316) ~[paper-1.20.4.jar:git-Paper-485]
        at de.bluecolored.bluemap.bukkit.BukkitWorld.persistWorldChanges(BukkitWorld.java:74) ~[BlueMap-4.1-paper.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.flushWorldUpdates(Plugin.java:573) ~[BlueMap-4.1-paper.jar:?]
        at de.bluecolored.bluemap.common.plugin.commands.Commands.lambda$updateCommand$16(Commands.java:742) ~[BlueMap-4.1-paper.jar:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
[17:00:01 WARN]: Exception in thread "BlueMap-Plugin-UpdateCommand" java.lang.IllegalStateException: Asynchronous world save!
[17:00:01 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[17:00:01 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.save(CraftWorld.java:1316)
[17:00:01 WARN]:        at BlueMap-4.1-paper.jar//de.bluecolored.bluemap.bukkit.BukkitWorld.persistWorldChanges(BukkitWorld.java:74)
[17:00:01 WARN]:        at BlueMap-4.1-paper.jar//de.bluecolored.bluemap.common.plugin.Plugin.flushWorldUpdates(Plugin.java:573)
[17:00:01 WARN]:        at BlueMap-4.1-paper.jar//de.bluecolored.bluemap.common.plugin.commands.Commands.lambda$updateCommand$16(Commands.java:742)
[17:00:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)

### Context
 - BlueMap-4.1-paper.jar send an error
 - BlueMap-4.1-spigot.jar no problem run a commend
 - paper-1.20.4-485.jar
 - purpur-1.20.4-2171.jar
 - use default config server and plugin
 - plugin only edit setting accept-download: true

![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/76953171/1366a0b9-38f2-42b1-a7e7-2dbd88c0aad5)

**Comment by TechnicJelle** [comment]
Thanks for reporting this bug!

This is a bug that has already been fixed in a0e91803608050f1014c43a9d27492348c10393d.
The fix just hasn't been released yet.

If you accept a potentially unstable experience (even more unstable than snapshots or pre-releases), then you can try using the latest development build of BlueMap:
1. Make sure you're logged into your GitHub account
2. Then you can go to this link: <https://github.com/BlueMap-Minecraft/BlueMap/actions>
3. Open the newest successful Build workflow run (Click the top one that has a ✅ next to it)
4. Then scroll down until you see "artifacts"
5. Download it to get a zip full of BlueMap jars
6. Extract the one for your platform, and use that instead of the version you're using right now

**Comment by KaBoom13** [comment]
okey thanks
