### ISSUE TITLE
error when having a huge map

### ISSUE THREAD

**Issue by PtitLegume** [BlueMap-Minecraft/BlueMap#541]
### What i did / Steps to reproduce

Just using the plugin
### Expected result

work
### Actual result

error

### Context
**BlueMap Version:**  
`3.20-forge-1.20.6`

```
[13273.582s][warning][gc,alloc] Worker-Main-2: Retried waiting for GCLocker too often allocating 262147 words
[21:58:35] [Worker-Main-2/ERROR]: Caught exception in thread Thread[#32,Worker-Main-2,5,main]
java.lang.OutOfMemoryError: Java heap space
at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.clone(Long2ObjectOpenHashMap.java:1336) ~[fastutil-8.5.12.jar:?]
at net.minecraft.world.level.lighting.LightEngineStorageBlock$a.a(SourceFile:36) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
at net.minecraft.world.level.lighting.LightEngineStorageBlock$a.b(SourceFile:29) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
at net.minecraft.world.level.lighting.LightEngineStorage.b(SourceFile:287) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
at net.minecraft.world.level.lighting.LightEngine.a(SourceFile:180) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
at net.minecraft.world.level.lighting.LevelLightEngine.a(SourceFile:53) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
at net.minecraft.server.level.LightEngineThreaded.f(SourceFile:187) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
at net.minecraft.server.level.LightEngineThreaded.h(SourceFile:166) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
at net.minecraft.server.level.LightEngineThreaded$$Lambda/0x00007f87f919e8c8.run(Unknown Source) ~[?:?]
at net.minecraft.util.thread.ThreadedMailbox.h(SourceFile:91) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
at net.minecraft.util.thread.ThreadedMailbox.a(SourceFile:146) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
at net.minecraft.util.thread.ThreadedMailbox.run(SourceFile:102) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

**Comment by TBlueF** [comment]
You probably just have not enough RAM allocated for the amount of mods on your server or something. BlueMap runs with very little available heap-memory..

Also you said you are using the **forge** version of bluemap, but your logs suggest that you are running **spigot**?
Note that hybrid-servers are not supported by bluemap.

If you still believe this is a BlueMap bug, please provide a HeapDump for me to analyze (`-XX:+HeapDumpOnOutOfMemoryError`).

If you need support, please use our [discord](https://discord.gg/zmkyJa3) :)
I will close this Issue and reopen it in case you provide a HeapDump.
