### ISSUE TITLE
Console Error on Player Logging Events

### ISSUE THREAD

**Issue by jcpt928** [BlueMap-Minecraft/BlueMap#546]
So, same version of everything.

SpongeVanilla - 1.20.6-11.0.0-RC1618-universal
BlueMap - 3.21 for 1.20.6

I get the following error on player login\logoff events, and this is probably why player markers don't show up on the map. This is not such a big deal at this time; and, it might be related to your comment regarding the API version, so, just giving you a heads up.

`[10:44:33] [Server thread/ERROR] [sponge]: Could not pass ServerSideConnectionEvent$Join$Impl to bluemap
java.lang.NoSuchFieldError: Class org.spongepowered.api.entity.living.player.gamemode.GameModes does not have member field 'org.spongepowered.api.registry.DefaultedRegistryReference NOT_SET'
        at de.bluecolored.bluemap.sponge.SpongePlayer.<clinit>(SpongePlayer.java:51) ~[SpongePlayer.class:?]
        at de.bluecolored.bluemap.sponge.SpongePlugin.onPlayerJoin(SpongePlugin.java:193) ~[SpongePlugin.class:?]
        at org.spongepowered.common.event.manager.RegisteredListener.handle(RegisteredListener.java:87) ~[RegisteredListener.class:1.20.6-11.0.0-RC1618]
        at org.spongepowered.common.event.manager.SpongeEventManager.post(SpongeEventManager.java:407) ~[SpongeEventManager.class:1.20.6-11.0.0-RC1618]
        at org.spongepowered.common.event.manager.SpongeEventManager.post(SpongeEventManager.java:437) ~[SpongeEventManager.class:1.20.6-11.0.0-RC1618]
        at org.spongepowered.common.SpongeCommon.post(SpongeCommon.java:123) ~[SpongeCommon.class:1.20.6-11.0.0-RC1618]
        at net.minecraft.server.players.PlayerList.handler$spongevanill$zie000$impl$onInitPlayer_join(PlayerList.java:1917) ~[?:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:290) ~[?:?]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:143) ~[?:?]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.md01a5ce$spongevanill$lambda$impl$onHandleConfigurationFinished$1$1(ServerConfigurationPacketListenerImpl.java:1118) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:162) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.redirect$spongevanill$zco000$tracker$wrapAndPerformContextSwitch(MinecraftServer.java:4693) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:841) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:168) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:823) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:817) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:145) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:792) ~[?:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:696) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:275) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
`

**Comment by TBlueF** [comment]
That is now an error caused by you using Sponge-API 11 while BlueMap-3.21-sponge is made for Sponge-API 8.2
Not a bug, just not compatible with your version.

I will probably update to API 10 next bluemap version since that seems to be the latest stable API release by sponge, that **might** help with compatibility in your case and fix your error.
