### ISSUE TITLE
Error - BlueMap + Residence add-on

### ISSUE THREAD

**Issue by filasik** [BlueMap-Minecraft/BlueMap#559]
### What i did / Steps to reproduce
Installed BlueMap - Residence

### Expected result
No error.

### Actual result
Working residence display on website:
http://82.208.17.85:29478/#spawn:10:59:22:59:-0.43:0.89:0:0:perspective

Error in console (every few minutes):
```
[13:21:05] [Server thread/WARN]: [BlueMap_Residence] Task #3020363 for BlueMap_Residence v2.8.1 generated an exception
java.lang.NoSuchMethodError: 'io.papermc.paper.plugin.configuration.PluginMeta org.bukkit.plugin.Plugin.getPluginMeta()'
at me.Mixer.bluemapresidence.Metrics.appendServiceData(Metrics.java:112) ~[?:?]
at me.Mixer.bluemapresidence.Metrics$MetricsBase.submitData(Metrics.java:234) ~[?:?]
at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1425) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

### Context
**BlueMap Version:**
```
bluemap version
[13:22:58] [Server thread/INFO]: Version: 5.2
[13:22:58] [Server thread/INFO]: Commit: 21738feb69f904df5f5cf61c907c7eda67911e0c
[13:22:58] [Server thread/INFO]: Implementation: spigot
[13:22:58] [Server thread/INFO]: Minecraft: 1.21
[13:22:58] [Server thread/INFO]: Render-threads: 0
[13:22:58] [Server thread/INFO]: Available processors: 24
[13:22:58] [Server thread/INFO]: Available memory: 2048 MiB
[13:22:58] [Server thread/INFO]: [copy to clipboard]
```

This is the installed plugin (add-on)
https://www.spigotmc.org/resources/bluemap-residence.107389/

**Comment by TBlueF** [comment]
This is an issue with the bluemap-residence addon, not with bluemap..
Please report this error to them :)
