### ISSUE TITLE
Frequent crash error in console.

### ISSUE THREAD

**Issue by ekul6547** [BlueMap-Minecraft/BlueMap#576]
### What i did / Steps to reproduce

Have a server, hosting via Ultraservers.com.
Bluemap v5.2, Bluemap map markers v2.1.3.
Many multiple server-side mods that add new biomes, structures, blocks (via Polymer) and stuff.
See context for mod list.

### Expected result
No errors when server is completely idle & nothing happening.

### Actual result
Keep getting this crash error:
```
09:47:55 [Thread-30234/WARN] Region-file watch-service for map 'world_the_nether' stopped unexpectedly! (This map might not update automatically from now on)
09:47:55 [Thread-30234/ERROR] Uncaught exception in thread "Thread-30234"
java.lang.NullPointerException: Cannot invoke "java.nio.file.WatchKey.reset()" because the return value of "java.nio.file.WatchService.poll(long, java.util.concurrent.TimeUnit)" is null
        at de.bluecolored.bluemap.core.util.FileHelper.awaitExistence(FileHelper.java:136) ~[BlueMap-5.2-fabric.jar:?]
        at de.bluecolored.bluemap.core.world.mca.MCAWorldRegionWatchService.take(MCAWorldRegionWatchService.java:84) ~[BlueMap-5.2-fabric.jar:?]
        at de.bluecolored.bluemap.common.plugin.MapUpdateService.run(MapUpdateService.java:68) ~[BlueMap-5.2-fabric.jar:?]
11:47:55 [Thread-30494/ERROR] Uncaught exception in thread "Thread-30494"
java.lang.NullPointerException: Cannot invoke "java.nio.file.WatchKey.reset()" because the return value of "java.nio.file.WatchService.poll(long, java.util.concurrent.TimeUnit)" is null
        at de.bluecolored.bluemap.core.util.FileHelper.awaitExistence(FileHelper.java:136) ~[BlueMap-5.2-fabric.jar:?]
        at de.bluecolored.bluemap.core.world.mca.MCAWorldRegionWatchService.take(MCAWorldRegionWatchService.java:84) ~[BlueMap-5.2-fabric.jar:?]
        at de.bluecolored.bluemap.common.plugin.MapUpdateService.run(MapUpdateService.java:68) ~[BlueMap-5.2-fabric.jar:?]
```

Also, I'm not 100% sure, but I believe this error is causing a memory leak in the server, as when generating a lot of new chunks, this error frequently pops up in the server logs, and memory usage just keeps increasing.

### Context
**BlueMap Version:**  
`BlueMap-5.2-fabric.jar`

<details>
<summary>Mod list</summary>

```
17:12:35 [main/INFO] Loading 211 mods:
        - armor-stand-editor 2.5.0+1.21-rc1
           |-- common-protection-api 1.0.0
           |-- fabric-permissions-api-v0 0.3.1
           |-- player-data-api 0.6.0+1.21
           |-- server_translations_api 2.3.1+1.21-pre2
           \-- sgui 1.6.0+1.21
        - balm-fabric 21.0.11
           \-- kuma_api 21.0.4
        - banners4bm 1.0.2+1.21
        - better-paths 1.0.0-1.21
        - bluemap 5.2
        - bmmarker 2.1.2
           |-- adventure-platform-fabric 5.14.0-SNAPSHOT
           |    |-- net_kyori_adventure-api 4.17.0
           |    |-- net_kyori_adventure-key 4.17.0
           |    |-- net_kyori_adventure-platform-api 4.3.3
           |    |-- net_kyori_adventure-text-logger-slf4j 4.17.0
           |    |-- net_kyori_adventure-text-minimessage 4.17.0
           |    |-- net_kyori_adventure-text-serializer-ansi 4.17.0
           |    |-- net_kyori_adventure-text-serializer-gson 4.17.0
           |    |-- net_kyori_adventure-text-serializer-json 4.17.0
           |    |-- net_kyori_adventure-text-serializer-plain 4.17.0
           |    |-- net_kyori_ansi 1.0.3
           |    |-- net_kyori_examination-api 1.3.0
           |    |-- net_kyori_examination-string 1.3.0
           |    \-- net_kyori_option 1.0.0
           |-- de_miraculixx_bmm-core 2.1.3
           |-- de_miraculixx_mc-commons 1.0.1
           |-- net_kyori_examination-api 1.3.0
           |-- net_kyori_examination-string 1.3.0
           \-- org_yaml_snakeyaml 2.2
        - brewery 0.8.0+1.21-rc1
           |-- net_objecthunter_exp4j 0.4.8
           |-- server_translations_api 2.3.1+1.21-pre2
           \-- sgui 1.6.0+1.21
        - cavespiderspawn 1.1
        - cc-tweaked-polymer-patch 1.111.0.2+1.21
           |-- factorytools 0.3.1+1.21
           |-- map-canvas-api 0.4.1+1.21
           |-- player-data-api 0.6.0+1.21
           \-- sgui 1.6.0+1.21
        - chunky 1.4.16
        - cloth-config 15.0.127
           \-- cloth-basic-math 0.6.1
        - collective 7.70
        - compacthelpcommand 2.6
        - computercraft 1.111.0
           |-- cc_tweaked_cobalt 0.9.3
           |-- com_jcraft_jzlib 1.1.3
           |-- io_netty_netty-codec-http 4.1.97
           |-- io_netty_netty-codec-socks 4.1.97
           \-- io_netty_netty-handler-proxy 4.1.97
        - darksmelting 1.1.5
        - directionhud 1.7.1+1.21
        - diversity 1.2.0+1.21
           |-- fabric-permissions-api-v0 0.3.1
           |-- org_javassist_javassist 3.28.0-GA
           \-- org_reflections_reflections 0.10.2
        - doors-closed 1.0.0+1.19.4
        - edibles 4.3
        - explorify 1.6.1
        - eyespy 1.3.7+1.21
           |-- jackfredlib-base 1.4.0+1.21
           |-- jackfredlib-colour 1.1.0+1.21
           |-- jackfredlib-config 0.2.3+1.21
           |    |-- blue_endless_jankson 1.2.3
           |    |-- commons-io_commons-io 2.15.1
           |    \-- jackfredlib-base 1.4.0+1.21
           |-- jackfredlib-lying 0.5.5+1.21
           |-- jackfredlib-toasts 1.1.0+1.21
           \-- server_translations_api 2.3.1+1.21-pre2
        - fabric-api 0.100.6+1.21
           |-- fabric-api-base 0.4.42+6573ed8cd1
           |-- fabric-api-lookup-api-v1 1.6.67+b5597344d1
           |-- fabric-biome-api-v1 13.0.28+6fc22b99d1
           |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
           |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
           |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
           |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
           |-- fabric-command-api-v1 1.2.49+f71b366fd1
           |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
           |-- fabric-commands-v0 0.2.66+df3654b3d1
           |-- fabric-content-registries-v0 8.0.14+b5597344d1
           |-- fabric-convention-tags-v1 2.0.17+7f945d5bd1
           |-- fabric-convention-tags-v2 2.4.1+86024ea6d1
           |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
           |-- fabric-data-attachment-api-v1 1.1.24+6a6dfa19d1
           |-- fabric-data-generation-api-v1 20.2.11+16c4ae25d1
           |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
           |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
           |-- fabric-events-interaction-v0 0.7.10+e633f883d1
           |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
           |-- fabric-item-api-v1 11.0.0+afdfc921d1
           |-- fabric-item-group-api-v1 4.1.2+78017270d1
           |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
           |-- fabric-keybindings-v0 0.2.45+df3654b3d1
           |-- fabric-lifecycle-events-v1 2.3.11+8f3583aed1
           |-- fabric-loot-api-v2 3.0.12+3f89f5a5d1
           |-- fabric-loot-api-v3 1.0.0+3f89f5a5d1
           |-- fabric-message-api-v1 6.0.13+6573ed8cd1
           |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
           |-- fabric-networking-api-v1 4.2.0+ab7edbacd1
           |-- fabric-object-builder-api-v1 15.1.12+d1321076d1
           |-- fabric-particles-v1 4.0.2+6573ed8cd1
           |-- fabric-recipe-api-v1 5.0.10+65089712d1
           |-- fabric-registry-sync-v0 5.0.24+6ced4dd9d1
           |-- fabric-renderer-api-v1 3.3.0+0ae0b97dd1
           |-- fabric-renderer-indigo 1.6.5+48fb1586d1
           |-- fabric-renderer-registries-v1 3.2.67+df3654b3d1
           |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
           |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
           |-- fabric-rendering-v0 1.1.70+df3654b3d1
           |-- fabric-rendering-v1 5.0.4+5a8c785ed1
           |-- fabric-resource-conditions-api-v1 4.2.1+d153f344d1
           |-- fabric-resource-loader-v0 1.1.5+78017270d1
           |-- fabric-screen-api-v1 2.0.24+b5597344d1
           |-- fabric-screen-handler-api-v1 1.3.81+b5597344d1
           |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
           |-- fabric-transfer-api-v1 5.1.15+3dccd343d1
           \-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8cd1
        - fabric-language-kotlin 1.11.0+kotlin.2.0.0
           |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
           |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
           |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
           |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
           |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
           |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
           \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
        - fabricloader 0.15.11
           \-- mixinextras 0.3.5
        - farmtweaks 1.1+1.21
        - ferritecore 7.0.0
        - glideaway 1.2.0+1.21
           \-- common-protection-api 1.0.0
        - healingcampfire 5.4
        - hearths 1.0.1
        - hopobettermineshaft 1.2.4
        - hopobetterruinedportal 1.4.2
        - hopobetterunderwaterruins 1.1.8
        - illagerexp 1.2.0
           |-- mm 2.3
           |-- server_translations_api 2.3.1+1.21-pre2
           \-- sgui 1.6.0+1.21
        - inventorymaker 1.3.0+1.21
           \-- fabric-permissions-api-v0 0.3.1
        - java 21
        - justmobheads 7.9
        - justplayerheads 4.0
        - leaves_us_in_peace 1.1.1
        - lithium 0.12.5
        - mes 1.3.2-1.21-fabric
        - midnightlib 1.5.7
        - minecraft 1.21
        - mns 1.0.2-1.21-fabric
        - mob_armor_trims 2.2.0
           |-- com_electronwill_night-config_core 3.7.1
           \-- com_electronwill_night-config_toml 3.7.1
        - mobfilter 0.10.0+1.21
        - modernfix 5.18.5+mc1.21
        - modviewer 1.8.1
           \-- fabric-permissions-api-v0 0.3.1
        - monsters_in_the_closet 1.0.3+1.21
        - mr_beyondenchant 1.2.0
        - mr_dragonkind_evolved 1.5
        - mr_dungeons_andtaverns 1-v4.3
        - mr_fortunate_ancientdebris 1.1
        - mr_just_anotherstructurepack 1.9
        - mr_neoenchant 5.4.0
        - mr_remove_terralithintromessage 1.0
        - mr_tidal_towns 1.3.2
        - mr_yggdrasil_structure 1.3.0
        - mvs 4.1.3-1.21-fabric
        - mysql-jdbc 8.0.33+20230506
        - natural_size_variation 1.0
        - netherportalfix 21.0.2
        - noisium 2.2.0+mc1.21
           \-- mixinextras 0.3.5
        - nullium 0.4.0
           \-- server_translations_api 2.3.1+1.21-pre2
        - nullscape 1.2.6
        - oplock 1.0.0+1.21
        - oreharvester 1.2
        - ouch 1.1.0+1.21
           |-- placeholder-api 2.4.0+1.21
           \-- predicate-api 0.5.2+1.21
        - polydecorations 0.4.2+1.21
           |-- common-protection-api 1.0.0
           |-- factorytools 0.3.1+1.21
           |-- map-canvas-api 0.4.1+1.21
           \-- sgui 1.6.0+1.21
        - polydex 1.2.2+1.21
           |-- placeholder-api 2.4.0+1.21
           |-- player-data-api 0.6.0+1.21
           |-- server_translations_api 2.3.1+1.21-pre2
           |-- sgui 1.6.0+1.21
           \-- sidebar-api 0.5.0+1.21
        - polyfactory 0.4.0-pre.5+1.21
           |-- common-protection-api 1.0.0
           |-- factorytools 0.3.1+1.21
           |-- graphlib 2.0.0-beta.1+1.21
           |    |-- codextra 2.0.0+1.21
           |    \-- common_events 1.0.0+1.21
           |-- sgui 1.6.0+1.21
           \-- sidebar-api 0.5.0+1.21
        - polymer-bundled 0.9.4+1.21
           |-- polymer-autohost 0.9.4+1.21
           |-- polymer-blocks 0.9.4+1.21
           |-- polymer-common 0.9.4+1.21
           |    \-- packet_tweaker 0.5.4+1.20.6
           |-- polymer-core 0.9.4+1.21
           |    |-- polymer-networking 0.9.4+1.21
           |    |    \-- polymer-common 0.9.4+1.21
           |    |         \-- packet_tweaker 0.5.4+1.20.6
           |    \-- polymer-registry-sync-manipulator 0.9.4+1.21
           |-- polymer-resource-pack 0.9.4+1.21
           |    \-- polymer-common 0.9.4+1.21
           |         \-- packet_tweaker 0.5.4+1.20.6
           \-- polymer-virtual-entity 0.9.4+1.21
                \-- polymer-common 0.9.4+1.21
                     \-- packet_tweaker 0.5.4+1.20.6
        - quickpaths 3.4
        - readyplayerfun 2.8.1.0
           \-- spectrelib 0.17.0+1.21
        - roguelike 2.0.7-1.21-fabric
        - servercore 1.5.3+1.21
           |-- fabric-permissions-api-v0 0.3.1
           |-- org_yaml_snakeyaml 2.2
           |-- space_arim_dazzleconf_dazzleconf-core 1.3.0-M2
           \-- space_arim_dazzleconf_dazzleconf-ext-snakeyaml 1.3.0-M2
        - serveruifix 0.3.0+1.21
           \-- sgui 1.6.0+1.21
        - sessility 0.6.1
        - silk-all 1.10.7
           |-- silk-commands 1.10.7
           |-- silk-core 1.10.7
           |-- silk-game 1.10.7
           |-- silk-igui 1.10.7
           |-- silk-nbt 1.10.7
           |-- silk-network 1.10.7
           \-- silk-persistence 1.10.7
        - skipservercheck 1.0.0
        - spark 1.10.73
           \-- fabric-permissions-api-v0 0.3.1
        - styled-nicknames 1.6.0+1.21
           |-- fabric-permissions-api-v0 0.3.1
           \-- player-data-api 0.6.0+1.21
        - taxfreelevels 1.3.12
        - terrablender 4.0.0.1
        - terralith 2.5.3
        - thoroughfabric 1.2.1+1.21
        - ticket-of-eternal-keep 1.2.1-1.21
           \-- server_translations_api 2.3.1+1.21-pre2
        - treeharvester 8.9
        - trinkets 3.10.0+polymerport.1
           |-- cardinal-components-base 6.1.0
           |-- cardinal-components-entity 6.1.0
           |-- player-data-api 0.6.0+1.21
           |-- server_translations_api 2.3.1+1.21-pre2
           \-- sgui 1.6.0+1.21
        - usefulrottenflash 1.0.1-1.21
        - welcomemessage 2.5
        - wooltweaks 3.5
        - wwoo 2.3.4
        - zombiehorsespawn 5.0
```
</details>

**Comment by TBlueF** [comment]
Known bug, fixed already with dbd74145423eefd366bb1e8da78fcd8cd7bb4cc9. (Next release) Completely harmless, you can ignore it safely :)
