### ISSUE TITLE
lost connection: The server is still loading, please, wait a bit and try joining again.

### ISSUE THREAD

**Issue by ruk13xa** [BlueMap-Minecraft/BlueMap#578]
### Actual result
It kicks player with the message: "lost connection: The server is still loading, please, wait a bit and try joining again."

### Context
BlueMap-5.3-spigot.jar

<!-- 
linux
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/3e707a7a-d635-4ac5-b113-b5c382fa5ab5">
<img width="563" alt="image" src="https://github.com/user-attachments/assets/19e04541-480a-44cf-ab27-f3f8743f316a">

Also:
2|kr_smp  | [21:53:44 ERROR]: [BlueMap] Unexpected error handling request
2|kr_smp  | java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "de.bluecolored.bluemap.common.serverinterface.ServerWorld.equals(Object)" because the return value of "de.bluecolored.bluemap.common.serverinterface.Player.getWorld()" is null
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[?:?]
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[?:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.accept(HttpConnection.java:86) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.accept(HttpConnection.java:40) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.Server.selection(Server.java:88) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:297) ~[?:?]
2|kr_smp  |     at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:201) ~[?:?]
2|kr_smp  |     at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:141) ~[?:?]
2|kr_smp  |     at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130) ~[?:?]
2|kr_smp  |     at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:168) ~[?:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.Server.run(Server.java:78) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  | Caused by: java.lang.NullPointerException: Cannot invoke "de.bluecolored.bluemap.common.serverinterface.ServerWorld.equals(Object)" because the return value of "de.bluecolored.bluemap.common.serverinterface.Player.getWorld()" is null
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.live.LivePlayersDataSupplier.get(LivePlayersDataSupplier.java:64) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.live.LivePlayersDataSupplier.get(LivePlayersDataSupplier.java:40) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.update(CachedRateLimitDataSupplier.java:56) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.get(CachedRateLimitDataSupplier.java:47) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.get(CachedRateLimitDataSupplier.java:30) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.JsonDataRequestHandler.handle(JsonDataRequestHandler.java:51) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.RoutingRequestHandler.handle(RoutingRequestHandler.java:79) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.BlueMapResponseModifier.handle(BlueMapResponseModifier.java:49) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.RoutingRequestHandler.handle(RoutingRequestHandler.java:79) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.LoggingRequestHandler.handle(LoggingRequestHandler.java:70) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.lambda$accept$0(HttpConnection.java:87) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
2|kr_smp  |     ... 11 more
2|kr_smp  |     Suppressed: java.io.IOException: Incomplete document
2|kr_smp  |             at com.google.gson.stream.JsonWriter.close(JsonWriter.java:610) ~[gson-2.10.1.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.live.LivePlayersDataSupplier.get(LivePlayersDataSupplier.java:56) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.live.LivePlayersDataSupplier.get(LivePlayersDataSupplier.java:40) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.update(CachedRateLimitDataSupplier.java:56) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.get(CachedRateLimitDataSupplier.java:47) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.get(CachedRateLimitDataSupplier.java:30) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.JsonDataRequestHandler.handle(JsonDataRequestHandler.java:51) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.RoutingRequestHandler.handle(RoutingRequestHandler.java:79) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.BlueMapResponseModifier.handle(BlueMapResponseModifier.java:49) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.RoutingRequestHandler.handle(RoutingRequestHandler.java:79) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.LoggingRequestHandler.handle(LoggingRequestHandler.java:70) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.lambda$accept$0(HttpConnection.java:87) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
2|kr_smp  |             at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[?:?]
2|kr_smp  |             at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[?:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.accept(HttpConnection.java:86) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.accept(HttpConnection.java:40) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.Server.selection(Server.java:88) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:297) ~[?:?]
2|kr_smp  |             at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:201) ~[?:?]
2|kr_smp  |             at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:141) ~[?:?]
2|kr_smp  |             at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130) ~[?:?]
2|kr_smp  |             at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:168) ~[?:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.Server.run(Server.java:78) ~[BlueMap-5.3-spigot.jar:?]

**Comment by ruk13xa** [comment]
<img width="563" alt="image" src="https://github.com/user-attachments/assets/18bdf1e6-85ad-4784-ad2f-bfc43bef743b">

**Comment by ruk13xa** [comment]
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/66a2f475-d169-4e92-88d5-7bf807a4d848">

**Comment by ruk13xa** [comment]
```
2|kr_smp  | [21:53:44 ERROR]: [BlueMap] Unexpected error handling request
2|kr_smp  | java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "de.bluecolored.bluemap.common.serverinterface.ServerWorld.equals(Object)" because the return value of "de.bluecolored.bluemap.common.serverinterface.Player.getWorld()" is null
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[?:?]
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[?:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.accept(HttpConnection.java:86) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.accept(HttpConnection.java:40) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.Server.selection(Server.java:88) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:297) ~[?:?]
2|kr_smp  |     at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:201) ~[?:?]
2|kr_smp  |     at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:141) ~[?:?]
2|kr_smp  |     at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130) ~[?:?]
2|kr_smp  |     at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:168) ~[?:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.Server.run(Server.java:78) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  | Caused by: java.lang.NullPointerException: Cannot invoke "de.bluecolored.bluemap.common.serverinterface.ServerWorld.equals(Object)" because the return value of "de.bluecolored.bluemap.common.serverinterface.Player.getWorld()" is null
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.live.LivePlayersDataSupplier.get(LivePlayersDataSupplier.java:64) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.live.LivePlayersDataSupplier.get(LivePlayersDataSupplier.java:40) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.update(CachedRateLimitDataSupplier.java:56) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.get(CachedRateLimitDataSupplier.java:47) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.get(CachedRateLimitDataSupplier.java:30) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.JsonDataRequestHandler.handle(JsonDataRequestHandler.java:51) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.RoutingRequestHandler.handle(RoutingRequestHandler.java:79) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.BlueMapResponseModifier.handle(BlueMapResponseModifier.java:49) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.RoutingRequestHandler.handle(RoutingRequestHandler.java:79) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.LoggingRequestHandler.handle(LoggingRequestHandler.java:70) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.lambda$accept$0(HttpConnection.java:87) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
2|kr_smp  |     ... 11 more
2|kr_smp  |     Suppressed: java.io.IOException: Incomplete document
2|kr_smp  |             at com.google.gson.stream.JsonWriter.close(JsonWriter.java:610) ~[gson-2.10.1.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.live.LivePlayersDataSupplier.get(LivePlayersDataSupplier.java:56) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.live.LivePlayersDataSupplier.get(LivePlayersDataSupplier.java:40) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.update(CachedRateLimitDataSupplier.java:56) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.get(CachedRateLimitDataSupplier.java:47) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.CachedRateLimitDataSupplier.get(CachedRateLimitDataSupplier.java:30) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.JsonDataRequestHandler.handle(JsonDataRequestHandler.java:51) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.RoutingRequestHandler.handle(RoutingRequestHandler.java:79) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.BlueMapResponseModifier.handle(BlueMapResponseModifier.java:49) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.RoutingRequestHandler.handle(RoutingRequestHandler.java:79) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.LoggingRequestHandler.handle(LoggingRequestHandler.java:70) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.lambda$accept$0(HttpConnection.java:87) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
2|kr_smp  |             at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[?:?]
2|kr_smp  |             at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[?:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.accept(HttpConnection.java:86) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.HttpConnection.accept(HttpConnection.java:40) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.Server.selection(Server.java:88) ~[BlueMap-5.3-spigot.jar:?]
2|kr_smp  |             at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:297) ~[?:?]
2|kr_smp  |             at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:201) ~[?:?]
2|kr_smp  |             at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:141) ~[?:?]
2|kr_smp  |             at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130) ~[?:?]
2|kr_smp  |             at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:168) ~[?:?]
2|kr_smp  |             at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.web.http.Server.run(Server.java:78) ~[BlueMap-5.3-spigot.jar:?]
```

**Comment by ruk13xa** [comment]
P.S it wasn't issue with bluemap it was a problem with discordutils
