### ISSUE TITLE
MCARegion.iterateAllChunks() loop out exception log info 

### ISSUE THREAD

**Issue by IsNott** [BlueMap-Minecraft/BlueMap#587]
### What i did / Steps to reproduce

I added it a few days ago to my paper server.
**Checked issues #560 and #569,change useing version to 5.2.5-paper and 5.3-paper/spigot but console still loop exception log out.**

Every single plugins load and run just fine.
Agreed with ELUA.
Tested at local(win 10) and remote(linux) server.

### Expected result

Nothing exception log.
### Actual result

It seems that although there kept console error log, it does not affect the running of the program

**Is my config or something wrong?**
```
`[10:47:56 ERROR]: [BlueMap] RenderManager(0): WorkerThread(1): Exception while doing some work!
java.lang.IllegalArgumentException: null
        at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:383) ~[?:?]
        at de.bluecolored.bluemap.core.world.mca.region.MCARegion.iterateAllChunks(MCARegion.java:157) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.core.world.mca.MCAWorld.preloadRegionChunks(MCAWorld.java:194) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.core.world.World.preloadRegionChunks(World.java:92) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.init(WorldRegionRenderTask.java:142) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.doWork(WorldRegionRenderTask.java:162) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.CombinedRenderTask.doWork(CombinedRenderTask.java:56) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.RenderManager.doWork(RenderManager.java:318) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.RenderManager$WorkerThread.run(RenderManager.java:343) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
[10:47:56 ERROR]: [BlueMap] RenderManager(0): WorkerThread(0): Exception while doing some work!
java.lang.IllegalArgumentException: null
        at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:383) ~[?:?]
        at de.bluecolored.bluemap.core.world.mca.region.MCARegion.iterateAllChunks(MCARegion.java:157) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.core.world.mca.MCAWorld.preloadRegionChunks(MCAWorld.java:194) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.core.world.World.preloadRegionChunks(World.java:92) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.init(WorldRegionRenderTask.java:142) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.doWork(WorldRegionRenderTask.java:162) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.CombinedRenderTask.doWork(CombinedRenderTask.java:56) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.RenderManager.doWork(RenderManager.java:318) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]
        at de.bluecolored.bluemap.common.rendermanager.RenderManager$WorkerThread.run(RenderManager.java:343) ~[[卫星地图]BlueMap-5.2-5-paper.jar:?]`
```
### Context
**BlueMap Version:**  
**[any]**
`BlueMap-5.2-5-paper.jar`
`BlueMap-5.3-paper.jar`
`BlueMap-5.3-spigot.jar`

**Server-Version**:
`Paper 1.20.4`

**Comment by TBlueF** [comment]
Looks like you have a very big region-file somewhere ^^
Can you please check if this build https://github.com/BlueMap-Minecraft/BlueMap/actions/runs/10280498459 fixes your issue? :)

**Comment by IsNott** [comment]
It works, thanks for your help!!!  :)
