### ISSUE TITLE
Error: RenderManager(0): WorkerThread(0): Exception while doing some work! java.util.NoSuchElementException: There is no TagType for id: 102

### ISSUE THREAD

**Issue by chtko** [BlueMap-Minecraft/BlueMap#588]
### What i did / Steps to reproduce
Nothing, the error came from nowhere.
### Expected result
The whole console is full of errors.
### Actual result
The card itself works stably, but it is not pleasant to look at the console, which is all red. The error appears almost every ~10 seconds, which is why the entire console is in this error.

## Error:
```[18:38:36 ERROR]: [BlueMap] RenderManager(0): WorkerThread(0): Exception while doing some work!
java.util.NoSuchElementException: There is no TagType for id: 102
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.TagType.forId(TagType.java:62) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.NBTReader.readTag(NBTReader.java:464) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.NBTReader.peek(NBTReader.java:57) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.adapter.DefaultDeserializerFactory$DefaultAdapter.read(DefaultDeserializerFactory.java:151) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.BlueNBT.read(BlueNBT.java:200) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.BlueNBT.read(BlueNBT.java:196) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.BlueNBT.read(BlueNBT.java:204) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.core.map.renderstate.CellStorage.loadCell(CellStorage.java:92) ~[BlueMap-5.3-spigot.jar:?]
        at java.base/java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.core.map.renderstate.CellStorage.cell(CellStorage.java:86) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.core.map.renderstate.CellStorage.cell(CellStorage.java:82) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.core.map.renderstate.MapChunkState.get(MapChunkState.java:38) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.checkChunksHaveChanges(WorldRegionRenderTask.java:311) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.init(WorldRegionRenderTask.java:130) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.doWork(WorldRegionRenderTask.java:162) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.CombinedRenderTask.doWork(CombinedRenderTask.java:56) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.RenderManager.doWork(RenderManager.java:318) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.RenderManager$WorkerThread.run(RenderManager.java:343) ~[BlueMap-5.3-spigot.jar:?]
[18:38:36 ERROR]: [BlueMap] RenderManager(0): WorkerThread(1): Exception while doing some work!
java.util.NoSuchElementException: There is no TagType for id: 102
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.TagType.forId(TagType.java:62) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.NBTReader.readTag(NBTReader.java:464) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.NBTReader.peek(NBTReader.java:57) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.adapter.DefaultDeserializerFactory$DefaultAdapter.read(DefaultDeserializerFactory.java:151) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.BlueNBT.read(BlueNBT.java:200) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.BlueNBT.read(BlueNBT.java:196) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.shadow.bluenbt.BlueNBT.read(BlueNBT.java:204) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.core.map.renderstate.CellStorage.loadCell(CellStorage.java:92) ~[BlueMap-5.3-spigot.jar:?]
        at java.base/java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.core.map.renderstate.CellStorage.cell(CellStorage.java:86) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.core.map.renderstate.CellStorage.cell(CellStorage.java:82) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.core.map.renderstate.MapChunkState.get(MapChunkState.java:38) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.checkChunksHaveChanges(WorldRegionRenderTask.java:311) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.init(WorldRegionRenderTask.java:130) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.WorldRegionRenderTask.doWork(WorldRegionRenderTask.java:162) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.CombinedRenderTask.doWork(CombinedRenderTask.java:56) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.RenderManager.doWork(RenderManager.java:318) ~[BlueMap-5.3-spigot.jar:?]
        at BlueMap-5.3-spigot.jar/de.bluecolored.bluemap.common.rendermanager.RenderManager$WorkerThread.run(RenderManager.java:343) ~[BlueMap-5.3-spigot.jar:?]
```

### Context
I searched for an error on GitHub, found a similar error #234, did as it was written there, deleting `minecraft-client-1.20.6.jar`, 
it didn't help.
In folder: `./config`, there is no folder: `./bluemap`.
**BlueMap Version:**  `5.3  Spigot`.
**Minecraft:** `1.20.6`
**Server Core:** Paper
**OS:** Windows 10

**Comment by chtko** [comment]
Here are the plugins that are on the server, maybe they are a problem:
![image](https://github.com/user-attachments/assets/2f01d271-5a79-4538-b265-37f4a2984fa9)

**Comment by TBlueF** [comment]
The problem is that you probably have some corrupted map-state files, probably caused by a crash or error while bluemap was writing them. The bug is that bluemap should be able to recover from this and fix the file, instead of erroring over and over again :)

(Purging the entire map should fix the erroring on your end as well.)

**Comment by chtko** [comment]
> The problem is that you probably have some corrupted map-state files, probably caused by a crash or error while bluemap was writing them. The bug is that bluemap should be able to recover from this and fix the file, instead of erroring over and over again :)
> 
> (Purging the entire map should fix the erroring on your end as well.)


If I understood everything correctly, then I have to delete the data that is responsible for chunks on the map. Is everything right?

**Comment by TBlueF** [comment]
> If I understood everything correctly, then I have to delete the data that is responsible for chunks on the map. Is everything right?

`/bluemap purge <map>` ^^

**Comment by chtko** [comment]
> > If I understood everything correctly, then I have to delete the data that is responsible for chunks on the map. Is everything right?
> 
> `/bluemap purge <map>` ^^

Thanks a lot, I'll try to use the command now. I'll see if the error has been corrected or not

**Comment by chtko** [comment]
> > If I understood everything correctly, then I have to delete the data that is responsible for chunks on the map. Is everything right?
> 
> `/bluemap purge <map>` ^^

The team helped solve the problem. Thank you very much!
