### ISSUE TITLE
Map is dark on 1.16.2 fabric server

### ISSUE THREAD

**Issue by Glucy-2** [BlueMap-Minecraft/BlueMap#69]
![image](https://user-images.githubusercontent.com/53287753/90523187-2aa92800-e19f-11ea-9fa8-615c4621e886.png)

**Comment by TBlueF** [comment]
First, press the "clear tile cache" button in the menu.
If that does not help, try this:
https://github.com/BlueMap-Minecraft/BlueMap/wiki#q-i-have-a-black-map--a-lot-of-the-map-is-missing

**Comment by Glucy-2** [comment]
i deleted `bluemap/web/data` and rendered
but it is still dark
and where is the menu?

**Comment by TBlueF** [comment]
![image](https://user-images.githubusercontent.com/10765470/90532194-3d0f6b80-e177-11ea-85b2-38f57c82bf82.png)

**Comment by TBlueF** [comment]
Also:
- Have you tested `/bluemap debug` .. use that command ingame please and tell me what happens..
- Is there anything in `bluemap/web/data` now?
- do you use the builtin webserver or are you using an external one, like nginx or apache?
- do you have a live-version of that map that i can take a look at?

**Comment by Glucy-2** [comment]
tested `/bluemap debug` and its OK now
but please give 1.16.2 better support
it sometimes crashes when stopping the server.

**Comment by TBlueF** [comment]
"it sometimes crashes when stopping the server."
Do you have a Crash-Report / Log?

**Comment by Glucy-2** [comment]
here is the crash report:
[crash-2020-08-18_21.19.06-server.txt](https://github.com/BlueMap-Minecraft/BlueMap/files/5091275/crash-2020-08-18_21.19.06-server.txt)
````python
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 20-8-18 下午9:19
Description: Exception initializing level

java.lang.NoSuchMethodError: net.minecraft.class_3233.method_19506()Lnet/minecraft/class_3218;
	at net.minecraft.class_2794.handler$zbj000$generateFeatures(class_2794.java:544)
	at net.minecraft.class_2794.method_12102(class_2794.java:230)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2794.handler$zbj000$generateFeatures(class_2794.java:544)
	at net.minecraft.class_2794.method_12102(class_2794.java:230)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (-104,64,104), Chunk: (at 8,4,8 in -7,6; contains blocks -112,0,96 to -97,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 0 game time, 0 day time
	Level name: world
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:383)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:332)
	at net.minecraft.class_3176.method_3823(class_3176.java:174)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1246410688 bytes (1188 MB) / 1832386560 bytes (1747 MB) up to 3791650816 bytes (3616 MB)
	CPUs: 8
	JVM Flags: 0 total; 
	Fabric Mods: 
		bbor: BoundingBoxOutlineReloaded 2.3-1.16.1
		bluemap: BlueMap 0.10.1-mc1.16
		carpet: Carpet Mod in Fabric 1.4.9
		carpet-extra: Carpet Extra 1.4.8
		com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		fabric: Fabric API 0.18.0+build.397-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c4e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b4e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+02fb8fda4e
		fabricloader: Fabric Loader 0.9.1+build.205
		here: here 0.0.10-mc1.16
		jankson: Jankson 3.0.0+j1.2.0
		minecraft: Minecraft 1.16.2
		org_apache_commons_commons-compress: commons-compress 1.19
		org_tukaani_xz: xz 1.8
		phosphor: Phosphor 0.6.0+build.7
		player-roles: Player Roles 1.0.2
		textile_backup: Textile Backup 2.0.0-1.16.2
	Player Count: 0 / 20; []
	Data Packs: vanilla, fabric/fabric-tool-attribute-api-v1, fabric/player-roles
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
````

**Comment by TBlueF** [comment]
Thank you. Yes, that could be related to a difference between 1.16.1 and 1.16.2.. next version will probably be built for fabric 1.16.2
